### ISSUE TITLE
Add geometry to DataSet class

### ISSUE THREAD

**Issue by jsmariegaard** [DHI/mikeio#107]
I think the DataSet class should hold the geometry of the data like it already has information of the items and the time axis. Having the spatial axes corresponds to the the xarray Dataset http://xarray.pydata.org/en/stable/generated/xarray.Dataset.html .

This would allow for easier plotting straight from the Dataset and for saving the dataset to file, also interpolation and more. In case of Dfsu dataset it could reference the _Unstructured class. For Dfs1,2,3 it would be simpler.  

I imagine a workflow like this: 

    dfs = Dfsu("myfile.dfsu") 
    ds = dfs.read()
    # some manipulation, e.g. time_interp() 
    ds.plot()
    ds.to_dfsu("my_new_file.dfsu") # the dataset holds geometry, projection etc

or 

    dfs = Dfs2("myfile.dfs2")
    ds = dfs.read(items=["var1", "var3"])
    ds2 = ds.max() # find max of every time step
    ds2.to_dfs0("my_new_file.dfs0") 

This would require moving (or wrapping) functionality from Dfs-classes to the Dataset class. But at least in some cases, it would give a simpler workflow - especially in cases where you go from one file type to another. This is much closer to the xarray api.

**Comment by ecomodeller** [comment]
The second example doesn't require any geometry, and is possible due to this commit https://github.com/DHI/mikeio/pull/106/commits/32a269fcdb578b63d135e968598314e299353133

See example in this test:

https://github.com/DHI/mikeio/blob/2a0f7a44546fcb4a21fdbbbce84d0f6b9c881a9e/tests/test_dataset.py#L454-L463

**Comment by jsmariegaard** [comment]
Agree. That was a bad example. Aggregation to dfs0 will not benefit from this enhancement.

**Comment by ecomodeller** [comment]
Now we have geometry as an attribute on the Dataset and the newly created DataArray 🎉
