### ISSUE TITLE
Res1d support for more elements in MIKE URBAN/MIKE URBAN+?

### ISSUE THREAD

**Issue by AL89** [DHI/mikeio#115]
Hi

When I try to use the res1d module with MIKE 1D result files (.res1d) from MIKE URBAN, I can only return the links (reaches).

```
from mikeio import res1d
file = 'N1D_result.res1d'
resultData = res1d.open(file)

print(resultData.data_types) 
['WaterLevel', 'WaterVolume', 'Discharge', 'FlowVelocity']
```

For the variable `resultData` there is an attribute called `reach_names`, which prints the links of the MIKE URBAN model.

Is it possible to retrieve data from other elements, like nodes, basins or catchments? If not, is it added in future versions?

My .res1d result file written in the above code is attached.
[N1D_result.zip](https://github.com/DHI/mikeio/files/5423424/N1D_result.zip)

Thanks in advance!

**Comment by rhaDHI** [comment]
Working on it :-) 
See this PR: https://github.com/DHI/mikeio/pull/111
You can install the progress so far from my branch using:  pip install git+https://github.com/rhaDHI/mikeio.git@mike1d-res1d-queries
It has breaking changes and not done yet. Please feel free to add code.

**Comment by rhaDHI** [comment]
This is the same as https://github.com/DHI/mikeio/issues/56 right?

**Comment by AL89** [comment]
> Working on it :-)
> See this PR: #111
> You can install the progress so far from my branch using: pip install git+https://github.com/rhaDHI/mikeio.git@mike1d-res1d-queries
> It has breaking changes and not done yet. Please feel free to add code.

@rhaDHI I tried to install the git package you suggested.

When I try to import the res1d module now, it throws an error regarding `ResultDataQuery`:
```
from mikeio import res1d
Traceback (most recent call last):

  File "<ipython-input-5-b98234b7265c>", line 1, in <module>
    from mikeio import res1d

  File "C:\Anaconda3\lib\site-packages\mikeio\res1d.py", line 12, in <module>
    from DHI.Mike1D.ResultDataAccess import ResultData, ResultDataQuery

ImportError: cannot import name 'ResultDataQuery'
```

Do you or anyone know a workaround for this?

**Comment by rhaDHI** [comment]
Do you have pythonnet installed? This way of installing from a git repo will not install all dependencies.

**Comment by AL89** [comment]
> Do you have pythonnet installed? This way of installing from a git repo will not install all dependencies.

Yes, I have pythonnet installed. What alternate is there?

**Comment by rhaDHI** [comment]
Mikeio requirements are ["pythonnet", "numpy", "pandas", "scipy", "pyyaml"].
Please try pip-installing into a clean normal python environment. Not anaconda. 
I used the branch in production so it should work.

**Comment by rhaDHI** [comment]
You can also try the workarounds on the normal version mentioned here: https://github.com/DHI/mikeio/issues/56

**Comment by rhaDHI** [comment]
I was able to load your data using: 
`
from mikeio.res1d import read
data = read("N1D_result.res1d")
`

**Comment by AL89** [comment]
Hello again. I am not even able to install numpy or pandas in my regular Python environment (not Anaconda).
I don't know why, I guess it's why I use Anaconda - this is easier to use imo. 
But when trying to install `numpy` it comes up with with the error attached. Can't see what the problem is.
[error_numpy.txt](https://github.com/DHI/mikeio/files/5444664/error_numpy.txt)

Tried to update the Anaconda environment as well. Installing `mikeio` works perfectly, but I dare not installing your latest changes from your branch. I guess I have to wait for the next update - or whenever you release it :)

**Comment by rhaDHI** [comment]
Not sure what the numpy install problems are.
I made some more updates and hope that it passes review soon. Then you should be able to pip install. We haven't tested with python 3.9 yet though. Can see you used that in the log. 
I understand the dare to install from other branches. This is why I recommend a clean virtual environment so you don't mess with existing python installations and packages :)

**Comment by AL89** [comment]
> I understand the dare to install from other branches. This is why I recommend a clean virtual environment so you don't mess with existing python installations and packages :)

See, I guess my level of Python is still on beginner - I have no idea to use the benefits of a virtual environment. My philosophy is just: "It just have to work!" and `mikeio` does!

**Comment by rhaDHI** [comment]
@ecomodeller when releasing to pypi, we should bump to 0.6.0 due to breaking changes.

**Comment by ecomodeller** [comment]
I read your mind, so I have changed to 0.6.0 already.
