### ISSUE TITLE
Extracting dfs0 from large dfs2 files

### ISSUE THREAD

**Issue by Hendrik1987** [DHI/mikeio#117]
Dear mikeio team,
It would be great to get an `element` or `isel` argument for the dfs2 read method to address the problem/solution discussed here:
(https://stackoverflow.com/questions/64597708/extracting-dfs0-from-large-dfs2-files)
Keep up the great work. 
You are making our life easy :-) Hendrik

**Comment by ecomodeller** [comment]
I suggest you make a draft version, which handles your problem. It should be possible to get inspiration from the Dfsu class, where you can do this already.

Preferably along with an illustrating example.

The guidelines for contribution is [here](https://github.com/DHI/mikeio/blob/master/CONTRIBUTING.md), but if you get stuck, just let us know.

Remember that MIKE IO is an open source project, open to contributions 😃

**Comment by jsmariegaard** [comment]
#126 is ready for input

**Comment by ecomodeller** [comment]
@Hendrik1987 How about this workflow, does it solve your needs?

![image](https://user-images.githubusercontent.com/614215/166477559-93f60578-aa8e-4f0c-acce-c16311594888.png)

**Comment by Hendrik1987** [comment]
@ecomodeller Looks great. Let me test with some of my data. Which branch is it on (I am a bit lost with hashtags and links above, sorry).

**Comment by jsmariegaard** [comment]
This is the beta release (and on main)

    >pip install mikeio==1.0b0

**Comment by jsmariegaard** [comment]
@Hendrik1987 I just found some bugs in this. So wait a couple of days before you test this. I will let you know once we have merged the fixes to main.

**Comment by jsmariegaard** [comment]
@Hendrik1987, we are now ready. Please update from main or install beta2. 

    >pip install mikeio==1.0b2

**Comment by ecomodeller** [comment]
Bbox is wrong, it should be (xmin, ymin, xmax, ymax) in physical coordinates, not index.

**Comment by Hendrik1987** [comment]
thanks @ecomodeller , now it works.

Takes ~40min to load 1 year ERA5 for 5by5 from a NAS location:

![image](https://user-images.githubusercontent.com/29595985/169288182-6448dde6-55eb-4195-b020-2a2b9e0088b9.png)

I did then also compare a bit mikeio ds vs xarray ds. Aggregation and plotting behaves indeed very similar, so that is nice. (Some more attributes could possibly be passed in the `.to_xarray()`, but that is cosmetics...).

![image](https://user-images.githubusercontent.com/29595985/169288773-000423a2-bebe-4117-8ad8-c5a3c5dad3e2.png)

However, I do notice some difference in read and write performance of .dfs2 and .nc (this time to a local location).

![image](https://user-images.githubusercontent.com/29595985/169288833-fb95e24d-77b4-4ce6-ac9e-5418dd48c08c.png)

To me sufficient tools are now available to also deal with large dfs2 files.

Some thin wrappers could be considered in the future. For example interpolation via xarray, and automatically determining the bounding box, based on the location and interpolation method requested.

**Comment by ecomodeller** [comment]
![](https://imgs.xkcd.com/comics/optimization.png)

**Comment by jsmariegaard** [comment]
@Hendrik1987 40min to load a subset of a file is a very long time. How big is that file? and what is the time if the file is on your hard drive? 

Yesterday I processed a 163GB dfsu file with MIKE IO in 60seconds - including writing the result to a new file. That is the type of speed I would expect from MIKE IO.

**Comment by ecomodeller** [comment]
Please note that the area argument to the read method filters data after the entire file (in each timestep) has been read, thus the read speed is expected to be the same, but the memory needed for a subset should be smaller.

This is the same behavior with all tools for reading dfs files, relying on the same core library AFAIK.

**Comment by jsmariegaard** [comment]
> @jsmariegaard 106GB. The file lives on 'nas07'. I guess I can try the difference, though copying it to my local drive will be unpractical in the real case scenario. Did you loop through the entire content of that file within 60 seconds?!

It was just to split the issue of IO over the network and the IO capacity of mikeio (Mike core). For tracking the problem. Not as a suggestion for your work flow. It could also be tested with a smaller file.

**Comment by Hendrik1987** [comment]
> It could also be tested with a smaller file.

I guess that's what I tried with the last step in my example above (where `ds` is the mikieio dataset area subset of the large .dfs2).

- `ds.to_dfs('./test_subset.dfs2')` 44.2 s
- `xrds = ds.to_xarray()` 1.7 s
- `xrds.to_netcdf('./test_subset.nc')` 0.1 s
- `ds = mikeio.read('./test_subset.dfs2')` 1.3 s
- `xrds = xr.open_dataset('./test_subset.nc')` 0.1 s

Though the subset might have been too small to get meaningful results?

- test_subset.dfs2 2.79 MB
- test_subset.nc 2.70 MB
