### ISSUE TITLE
TypeError: No method matches given arguments for CreateTemporalEqCalendarAxis

### ISSUE THREAD

**Issue by bhlevca** [DHI/mikeio#118]
**Describe the bug**
Any dfs.write() call ends up with the error in the title.
I assume that the error comes from pythonnet/C#  as the last call I trace is going there.

Probably some dlls have changed but I am not in sync. Please advise.

**System information:**
 - Python version: 3.7
 - MIKE version: 2020

**Comment by ecomodeller** [comment]
Hi Bogdan, can you provide a minimal reproducible example? 

Is this referring to the released version from Pypi or from Github?

All tests are passing in Github Actions, so I suppose it should work as expected 😕

**Comment by bhlevca** [comment]
Hi Henrik,

You are right, I should have run the test before filing the report. 
I ran the tests and and they pass.

I always use the `github` version and never had any issues until now. But that does not seem to be my problem.
The problems seems to be the change in the API. 
`dfs.write` method had an argument `datetime` which in the new version is `dt`.  I did not change anything in the code but just replaced `datetime` wirh `dt` when my code failed too run.

I used to do something like this:

```
Time_Frame = []
for i in range(precipt.shape[0]):
                ts = float(data.GetRasterBand(i+1).GetMetadata()['GRIB_VALID_TIME'].split()[0])
                Time_Frame.append(datetime.fromtimestamp(ts))
```

and I was passing in write() `datetimes = Time_Frame`.  In the new code `dt = Time_Frame` fails with  the error put in the subject. 

Please note that `DFS0` still has the `datetimes ` argument, but` DFS2` doesn't.  This is inconsistent. I don't know whether this is intended or not but looks wrong. 

Also, the fact that all the tests pass doesn't always tell that something is wrong, especially if the tests have been modified.  This kind of changes break backward compatibility.


Please let me know if there is another way of doing not equidistant time as in your tests I only found `dt=12` which means equidistant units. Thanks

**Comment by ecomodeller** [comment]
You are correct. I removed the option of non-equidistant Dfs2 when I did some refactoring. Non-equidistant Dfs0 is very common, but the same is not true for Dfs2. In fact, if you try to create a Dfs2 from scratch with Mike Zero, there is only Equidistant time axis to choose from in the dropdown menu.
![image](https://user-images.githubusercontent.com/614215/98028210-14118500-1e0e-11eb-83f5-f0900c43b24c.png)

So in order to avoid creating files which are not fully supported, I decided to remove this option for now at least.

Do you have a valid use-case for non-equidistant Dfs2 files?

I don't think it can be used as forcing for Mike FM, since it interpolates assuming equidistant time, @jsmariegaard is this correct?

**Comment by bhlevca** [comment]
It depends from where I get the data, not all data on the internet is equidistant, but I agree with you that most is.  One nice thing would be if DFS2 would accept non equidistant data and interpolate it before saving it in the Mike format.  Of course, that could be done before using  mikeio.

**Comment by ecomodeller** [comment]
I know a lot of data that is not equidistant...

How about this approach, create a Dataset with non-equistant data (in this example, I am lazy and reading from an existing file, but you get the point, I am sure), interpolate it to equidistant and then write it to a file using Dfs2?

https://github.com/DHI/mikeio/blob/4c27546fdac327e89d708c728b99412bb8675204/tests/test_dfs2.py#L206-L228

Should work right?

In a not to distant future, I think we will only support Dataset as input to `dfs.write()`, and not raw list of numpy arrays...

**Comment by bhlevca** [comment]
This looks nice. 
Dataset, you mean a `pandas` dataset? Dataset has an index and that could solve all these issues. In that case a convenience method should be provided to convert from a` numpy` array to dataset.

**Comment by ecomodeller** [comment]
There is a mikeio [Dataset](https://github.com/DHI/mikeio/blob/4c27546fdac327e89d708c728b99412bb8675204/mikeio/dataset.py#L8), take a look at these tests https://github.com/DHI/mikeio/blob/4c27546fdac327e89d708c728b99412bb8675204/tests/test_dataset.py#L23

All dfs read methods returns a Dataset. And the write methods accepts list of numpy array or a Dataset
https://github.com/DHI/mikeio/blob/4c27546fdac327e89d708c728b99412bb8675204/mikeio/dfs2.py#L124

**Comment by bhlevca** [comment]
Thanks Henrik. I am not very knowledgeable about all the aspects of mikeio I used only a small subset of the API, mostly reading third party data and saving in Mike file formats, so I was not familiar with the Dataset. It seems to be similar to the pandas DataSeries (not DataFrame), in having the time dimension incorporated.
