### ISSUE TITLE
Support python 3.9

### ISSUE THREAD

**Issue by rhaDHI** [DHI/mikeio#123]
Start by adding test pipeline?

**Comment by ecomodeller** [comment]
Shapely is not supported on Python 3.9, but will be soon.
https://github.com/Toblerity/Shapely/issues/944

**Comment by ecomodeller** [comment]
Shapely is ok.
Now we have to wait for [Python.Net](https://github.com/pythonnet/pythonnet/pull/1264)

**Comment by jsmariegaard** [comment]
pythonnet is getting there https://github.com/pythonnet/pythonnet/pull/1264 - but do we need to wait for a release?

**Comment by ecomodeller** [comment]
I think we have wait a bit longer, I can not get numpy to work on Python 3.9.
