### ISSUE TITLE
Faster numpy operations

### ISSUE THREAD

**Issue by rhaDHI** [DHI/mikeio#130]
Could use Numba https://numba.pydata.org to speed up operations on large data.
It's basically just importing the package and adding a decorator to the calculation functions:
`from numba import jit
import random

@jit(nopython=True)
def monte_carlo_pi(nsamples):
    acc = 0
    for i in range(nsamples):
        x = random.random()
        y = random.random()
        if (x ** 2 + y ** 2) < 1.0:
            acc += 1
    return 4.0 * acc / nsamples`

**Comment by ecomodeller** [comment]
Yes, me and @jsmariegaard discussed this last week. Is there any downsides at all to including numba as a dependency?

I guess, it limits the use of custom classes in jitted functions, but I suppose that is an acceptable price for speed-up.

**Comment by jsmariegaard** [comment]
I think that numba could be used for some methods. Not for all the IO stuff of course - but e.g. for find area, volume and similar in dfsu files, interpolation etc.

**Comment by ecomodeller** [comment]
@rhaDHI Unless you have any specific suggestions on where to apply numba, I think we will close this isse.
