### ISSUE TITLE
Common File Formats to dfs2

### ISSUE THREAD

**Issue by spizwhiz** [DHI/mikeio#132]
I am having lots of issues trying to create a dfs2 for use in my model.  Have been trying to use the Grid2Mike utility but it seems like maybe it is having issues with nan values, so I am trying to do the conversion using this package.

The example notebooks all focus on using netcdf files, but it would be very nice to show how to convert some other data formats into form that can use the dfs.write or dfs.create functions.

Examples of file formats would include:  .asc, .tiff, .shp, .xyz

Many Thanks,

**Comment by ecomodeller** [comment]
* Asc is a text format (ASCII), and the description is [here](http://resources.esri.com/help/9.3/arcgisengine/java/GP_ToolRef/spatial_analyst_tools/esri_ascii_raster_format.htm), you should be able to read a few with a few lines of Python code including handling nan values.
* Tiff can be read in Python with [rasterio](https://rasterio.readthedocs.io/en/latest/)

* Shp is a general vector based format, for points, polylines, polygons, what type of data are you thinking about?

* xyz is a format for point data, would you like to interpolate the point values to a grid and save them as dfs2?

Please give a try, if you do not succeed, paste the code you used here!

**Comment by jsmariegaard** [comment]
You can also see examples of creating dfs2 files from 2d arrays in https://github.com/DHI/mikeio/blob/master/tests/test_dfs2.py
