### ISSUE TITLE
Dfsu to geotiff

### ISSUE THREAD

**Issue by Daldek** [DHI/mikeio#134]
**Describe the bug**
g.bbox.left causes error "AttributeError: 'list' object has no attribute 'left'"

**To Reproduce**
I was following the steps from the notebook

**Expected behavior**
g.bbox.left will return the left coordinate

**Screenshots**
![obraz](https://user-images.githubusercontent.com/38719982/99382193-71a4d780-28cc-11eb-84b7-e479b610e0ca.png)

**System information:**
 - Python version 3.7.9
 - MIKE 2019 Update 1, mikeio 0.6.0

**Comment by ecomodeller** [comment]
To be able to use named attributes on the bounding box, you need the development version of mikeio,
`pip install --upgrade https://github.com/DHI/mikeio/archive/master.zip`
