### ISSUE TITLE
Dfsu interpolation speed on large meshes

### ISSUE THREAD

**Issue by ecomodeller** [DHI/mikeio#136]
Interpolation (by default) does not extrapolate outside the domain.

https://github.com/DHI/mikeio/blob/ce09ed18739c948dc1e81601db5d16247cdc4621/mikeio/dfsu.py#L564

Obtaining the domain polygon (incl. holes) involves looping over all elements, which takes a lot of time for large meshes.
https://github.com/DHI/mikeio/blob/ce09ed18739c948dc1e81601db5d16247cdc4621/mikeio/dfsu.py#L197
https://github.com/DHI/mikeio/blob/ce09ed18739c948dc1e81601db5d16247cdc4621/mikeio/dfsu.py#L1060-L1069
Is is possible to get the domain poygon in a more efficient way? 

E.g. using only boundary nodes?

**Comment by jsmariegaard** [comment]
Yes. Let's avoid shapely. I'll cook something up
