### ISSUE TITLE
Cannot import mikeio on offline computer without MIKE software

### ISSUE THREAD

**Issue by laurafroelich** [DHI/mikeio#138]
**Describe the bug**
We have downloaded mikeio 0.6.0 and its dependencies from pypi. On computers with internet and preinstalled MIKE software, including MIKE Zero, we can install and import mikeio without a problem. However, on a computer without internet access and no preinstalled MIKE software, we get the error:

    mikeio\__init__.py:22: in <module>
    from .dfs0 import Dfs0
    mikeio\dfs0.py:8: in <module>
    from DHI.Generic.MikeZero import eumQuantity
    E   ModuleNotFoundError: No module named 'DHI.Generic.MikeZero'; 'DHI.Generic' is not a package

**To Reproduce**
On a computer with internet, download mikeio and dependencies:

    pip download mikeio -d mikeio_offline

Copy the folder mikeio_offline to a computer without internet and without preinstalled MIKE software, and run the following:

    pip install  mikeio --no-index --find-links=mikeio_offline

Then start python and type

    import mikeio

**Expected behavior**
Import of mikeio with no error messages

**Screenshots**

**System information:**
 - Python version: 3.7.7
 - MIKE version: 0.6.0

**Comment by ecomodeller** [comment]
Can you import any other .NET dll?

**Comment by rhaDHI** [comment]
It is the first dll import it meets. So not necessarily related to that specific dll but the whole bin folder that it cannot find.
The test pipeline runs in a new environment without MikeZero, and internet access should not matter?

**Comment by rhaDHI** [comment]
Maybe try mikeio 0.5.x before we updated MIKE dll's?

**Comment by ecomodeller** [comment]
> It is the first dll import it meets. So not necessarily related to that specific dll but the whole bin folder that it cannot find.
> The test pipeline runs in a new environment without MikeZero, and internet access should not matter?

Exactly, the test pipeline (Actions) runs on a server without MikeZero, which should eliminate any *"works on my machine"* problems.

**Comment by laurafroelich** [comment]
We initially tried with version 0.5.3 and updated to 0.6.0, hoping that would solve the issue

**Comment by laurafroelich** [comment]
I agree, internet access should not matter. However, it is the only difference between the machine we are trying to use mikeio on, and the test machines that run pipelines, that I could think of. There might be other differences of course, that have not occurred to me.

**Comment by rhaDHI** [comment]
32 bit problems?

**Comment by rhaDHI** [comment]
Maybe try to import a dll using pythonnet on the machine?

**Comment by rhaDHI** [comment]
@ecomodeller Why is there a __init__.py in the bin folder?

**Comment by ecomodeller** [comment]
In order to package the dll in the mikeio package.
See this commit: https://github.com/DHI/mikeio/commit/85117fb4abd80d3800e343922842116fd2032ad1

But it could be sufficient to have it in the MANIFEST.in ?

**Comment by laurafroelich** [comment]
We wanted to try to import another dll, but were unsure which non-MIKE dll would be suited for import. We tried a few that did not seem importable, with unrelated error messages. I don't have much experience with pythonnet and dlls, but assume not all dlls can be imported.

**Comment by ecomodeller** [comment]
Here is simple example to test a .NET dll (in zipfile, GitHub did not allow .dll 😿)


![image](https://user-images.githubusercontent.com/614215/99575597-20ced500-29d9-11eb-98c2-491a43983c72.png)

[LifeUniverse.zip](https://github.com/DHI/mikeio/files/5562145/LifeUniverse.zip)

**Comment by laurafroelich** [comment]
Thanks for all the comments and suggestions and the code example. We were able to run the code example and get the answer to life, the universe, and everything successfully on the problematic machine.

**Comment by laurafroelich** [comment]
@JesperGr do you have any ideas on something to try?

**Comment by JesperGr** [comment]
Assuming the version 0.6.0 of mikeio comes fully packed with all required files from MIKE Core, i.e. the .NET libraries like DHI.Generic.MikeZero.EUM.dll and DHI.Projections.dll, the native ones like eum.dll, ufs.dll etc., and a set of supporting files, like EUM.xml and ellipsoid.pfs etc. - right?

Two more things that the MIKE installer makes sure is installed, and which must be there: 

- .NET Framework 4.7.2 runtime.
-  Microsoft Visual C++ Redistributable ([link](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads))

I am not familiar with how Python reports errors for issues like this. For a .NET test application, in the former case it will complain about missing or incompatible .NET dll's, and in the latter case it will complain about missing native dll (eum.dll or ufs.dll).

**Comment by rhaDHI** [comment]
Yes, we included these dll's: https://github.com/DHI/mikeio/tree/master/mikeio/bin

**Comment by laurafroelich** [comment]
Yes,NET Framework 4.7.2 runtime and Microsoft Visual C++ Redistributable (link) are installed

**Comment by JesperGr** [comment]
Then I would make a small C# application that loads DHI.Generic.MikeZero.EUM and maybe also DHI.Generic.MikeZero.DFS, and run that. With that it is possible to check if the problem is related to the MIKE Core libraries, or with python loading of the MIKE Core libraries.

**Comment by rhaDHI** [comment]
The problem was python and for some obscure reason it worked upgrading python from 3.7 to 3.8.
