### ISSUE TITLE
Dfsu - Speed and direction  notebook example needs fixing

### ISSUE THREAD

**Issue by bhlevca** [DHI/mikeio#142]
Include code snippet

**Expected behavior**
Arrows should show. 
There is a simple fix.` dfs.plot()` returns the axis `ax` on which plots. You just need a small change to make it work and use the returned `ax` to call `quiver` not from `plt`:

```
ax = dfs.plot(cs, label="Current speed (m/s)")
ax.quiver(x, y, u, v, scale=6, minshaft=3)
```
The rest of the code can stay the same except delete
```
ax.set_ylim([None, ylim])
ax.set_xlim([xlim, None])
```
which are not only unnecessary but it will prevent proper rendering.

An example figure of quiver that works is attached
![LOntario_Vel-crop](https://user-images.githubusercontent.com/182494/99894464-cb512d00-2c51-11eb-872a-1bb43de90652.png)

It would be nice if we could distribute the velocity vectors on a fictive structured grid to avoid the concentration of vectors in the areas with small elements. Is there any way we can do it now?

**Comment by mohm-dhi** [comment]
Thanks Bogdan! 
One way to prevent having high density arrow in high resolution mesh is to create a grided data by interpolation from dfsu (dfsu to dfs2 converter) and do the quiver plot. Or you can: 
x = np.linspace(-80 ,-76, 200)
y = np.linspace(43, 44.5, 100)
[X, Y] = np.meshgrid(x, y) and then get the points values by interpolation and then do the quiver plot.
