### ISSUE TITLE
Cannot slice dfs0 in time if TimeAxisType.NonEquidistantCalendar

### ISSUE THREAD

**Issue by jsmariegaard** [DHI/mikeio#149]
If a dfs0 file has NonEquidistantCalendar axis I get an error when using the time_step slicing that I love so much:

Example:

    dfs = Dfs0('non_equidistant_file.dfs0')
    ds = dfs.read(time_steps='2018-1-1,2019-1-1 00:00')

I get the following error:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-14-3803e25cf71d> in <module>
----> 1 ds = dfs.read(time_steps='2018-1-1,2019-1-1 00:00')

d:\source\mikeio\mikeio\dfs0.py in read(self, items, time_steps)
    111         self._n_timesteps = dfs.FileInfo.TimeAxis.NumberOfTimeSteps
    112 
--> 113         items, item_numbers, _ = get_valid_items_and_timesteps(self, items, time_steps)
    114 
    115         dfs.Close()

d:\source\mikeio\mikeio\dutil.py in get_valid_items_and_timesteps(dfs, items, time_steps)
     38 
     39     if isinstance(time_steps, slice):
---> 40         freq = pd.tseries.offsets.DateOffset(seconds=dfs.timestep)
     41         time = pd.date_range(dfs.start_time, periods=dfs.n_timesteps, freq=freq)
     42         s = time.slice_indexer(time_steps.start, time_steps.stop)

AttributeError: 'Dfs0' object has no attribute 'timestep'

**Comment by jsmariegaard** [comment]
I was actually looking for the generic function extract_steps(start, end) which extracts time steps from a generic dfs file but could not find it...

**Comment by jsmariegaard** [comment]
a work-around is reading the whole time series first with ds =dfs.read() and then:

    mask = (ds.time>='2018') & (ds.time<='2019-1-1 00:00')
    ds2 = ds.isel(np.where(mask)[0], axis=0)

**Comment by ecomodeller** [comment]
Dfs0 files are usually small enough to fit in memory.

Did you try to subset the dataset instead?
```
dfs = Dfs0('non_equidistant_file.dfs0')
ds = dfs.read()
selds = ds["2018-01-01 00:00":"2019-01-01 00:00"]
```
