### ISSUE TITLE
Export mesh/dfs2/dfsu data to shapefiles/geotiffs

### ISSUE THREAD

**Issue by georgebv** [DHI/mikeio#155]
**Is your feature request related to a problem? Please describe.**
I want to be able to export mesh/dfs2/dfsu data to GIS formats

**Describe the solution you'd like**
DFSU has `to_shapely` method. I propose adding the following methods (to all dfsu/dfs2 and mesh when its implemented):
- `to_shapefile(path: typing.Union[str, pathlib.Path], item: str, timestep: datetime)` - writes dfsu/dfs2 timestep/item to an ESRI shapefile (polygons of triangular and/or rectangular shapes)
- `to_geotiff(path: typing.Union[str, pathlib.Path], item: str, timestep: datetime, resolution: float)` - creates a raster with resolution in meters with data for given item/timestep

**Describe alternatives you've considered**
Doing it separately, but this would defeat the purpose of using the `mikeio` library. I have already done this via DHI SDK, but having it natively in `mikeio` would be better.

**Additional context**
None.

**Comment by jsmariegaard** [comment]
Hi @georgebv , good points - have you seen the notebook https://github.com/DHI/mikeio/blob/master/notebooks/Dfsu%20-%20Export%20to%20shapefile.ipynb

**Comment by georgebv** [comment]
Hi @jsmariegaard , this looks good. It would be very useful if this was buil-in and accessible via a single method. Often we want to quickly visualize a mesh and having to write boilerplate code is boring.

As I looked at it, I have another suggestion: perhaphs you can add an argument to the proposed `to_shapefile` method called `feature_type`. It would have these options:
- "centroid" - exports points (centers of triangles/quads with elevations as attribute)
- "vertex" - same as "centroid", but exports vertices
- "polygon" - exports polygons (triangles/quads) with elevations as attribute
- "contour" - exports contours with elevations as attribute (for contour you might need additional argument for interval, which would be ignored for other options)

**Comment by jsmariegaard** [comment]
Good ideas. @georgebv would it possible for you to start a PR with some of this stuff?

**Comment by murray91** [comment]
I support adding this feature. I've been looking into it independently for some weeks now. From what I gather, DFSU files store points which are not necessarily in a grid format. If they're unordered points, there's various methods to interpolate to a grid (nearest neighbour, inverse distance weighted, bilinear interpolation, etc.). I've been trying to replicate how Mike Zero converts dfsu to dfs2, but no luck so far. It would be great if this feature had an option to use the same method as Mike Zero, and other methods. For myself, it's most important for it to replicate how Mike Zero converts the files.

**Comment by georgebv** [comment]
@murray91 this should be straightforward with scipy - especially since it's already required by the package. Basically the procedure would be as follows:

- create X, Y mesh using [`numpy.meshgrid`](https://numpy.org/doc/stable/reference/generated/numpy.meshgrid.html)
- interpolate Z using [`scipy.interpolate.griddata`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.griddata.html)
- export to a tiff raster file using GDAL - this is the tricky part because making this a requirement would make `mikeio` unusable to most users, because installing it on Windows requires additional actions (not just the usual `pip install`)

I have been thinking about this as well and I am hoping to get to this some time this winter.

@jsmariegaard what do you think about the GDAL part? A solution I propose is as follows: by default the method would return a tuple of X, Y, Z (each being 2D numpy.ndarray). If the user provides a `path` argument (indicating that they want to export it to tiff file), only then code checks if GDAL is available and attempts to use it. The import itself is attempted at the top of the script and, on failure, gdal is set to None.

**Comment by ecomodeller** [comment]
I also would like to highlight this [Dfsu interpolation notebook]( https://github.com/DHI/mikeio/blob/master/notebooks/Dfsu%20-%202D%20interpolation.ipynb) where there is an example of interpolation from dfsu to a structured grid and exported to Geotiff.

But I agree that if you use this functionality a lot you would like to have it in two lines of code.

I think it is a good compromise to use libraries not installed by default, as long as a proper documentation including a good error message if the user doesn't have it installed.

This approach is used by e.g. pandas when exporting to [parquet](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_parquet.html)

**Comment by ecomodeller** [comment]
Please take a look at the updated notebooks, where we believe this is simple by:
1. easy getting a Grid2D covering the Dfsu domain (or supplying a specific Grid2D)
2. interpolate to the grid using `interp_like`
3. Convert to desired format (NetCDF, GeoTiff) using 3rd party libraries, which we prefer not to have as dependencies for MIKE IO.
