### ISSUE TITLE
DFS.read() cannot read large dfsu files

### ISSUE THREAD

**Issue by bhlevca** [DHI/mikeio#159]
**Describe the bug**
I tried to read a large (11 GB) dfsu file with `dfs.read()` and it 'times out' or crashes  without giving an error or warning.

It works with a 5 GB dfsu file, sometimes, I needed 3 tries to make it read.

**To Reproduce**
   ```
 dfs = Dfsu(filename)
 print(">> reading {}".format(filename))
 ds = dfs.read()
 print(">> reading done!")
```

**Expected behavior**
I would expect to see _`>>reading done!`_ or an error message

**System information:**
 - Python version : 3.7
 - MIKE version :  master as of December 22, 2020

**Comment by jsmariegaard** [comment]
Do you have enough memory to do the operation? (try to monitor during read)

Also, this related scenario could be relevant for you: https://github.com/DHI/mikeio/blob/21893287f0ed8448bcd2d64c79c9f6f425214ce7/tests/test_dfsu.py#L643 for handling larger than memory files.

**Comment by bhlevca** [comment]
I am working remotely on a laptop these days.  It still has 16 GB of memory and my initial guess was that the memory was the problem. 
I can definitely read several time steps at a time circumvent the limitation.
Nevertheless, the program/app should not silently quit, in my opinion.  An error message should be printed, similarly to what `vscode`  does in such situations.    Perhaps  adding a memory monitoring function during the `dfs.read()`

**Comment by jsmariegaard** [comment]
I totally agree with you - mikeio should silently quit. And thanks for the suggestion!

**Comment by NautilusChan** [comment]
but, how to paginate?

**Comment by ecomodeller** [comment]
In version 1.0 ways to subset in items, time or space which will allow you to read a big file in chunks. There is also functionality in the generic module to handle big files.
