### ISSUE TITLE
Dfs3 layer number for the bottom should be 1. 

### ISSUE THREAD

**Issue by mohm-dhi** [DHI/mikeio#161]
I understand that you created a method "flipup" to flip the data upside down but technically when we look at ta 3D file, the first layer is the bottom layer, so by default it should be like that and if user wanted to make it upside down that method can be used. 

In addition, layer number should be different from index number as it makes more sense to say layer 1 instead of layer 0. So in the method Dfs3.read(layers= None) should get the layer number instead of index number.  

Thanks,

**Comment by jsmariegaard** [comment]
Dfs3 has been refactored. Please have a look. Layer numbering is consistent with standard python indexing and the rest of MIKE IO and they, therefore, start at 0. This is of course inconsistent with MIKE Zero but we cannot be consistent with both.
