### ISSUE TITLE
Dfs3 to return the bottom values 

### ISSUE THREAD

**Issue by mohm-dhi** [DHI/mikeio#162]
It would be very useful to have a method to return the bottom values of a 3D file. If the 3D file represent data for a lake (lets say water temperature) so depend on the depth of each cell column some values at the bottom of the lake is nan values but we are interested to just have the bottom non-nan values. 

![image](https://user-images.githubusercontent.com/65772896/103367453-1bae7c80-4a93-11eb-82af-55dd6be3203d.png)

in the above figure you can see a cross section of the lake so I am interested to get all the bottom values showed by blue line and save it as a dfs2 file. 

Another very good feature is to have a method to return the data at any height above the lake bed. 

Please let me know if you need more information. 

Thanks,

**Comment by ecomodeller** [comment]
Seems relevant. But since the widespread use of MIKE FM, dfs3 files are not so popular anymore. For myself, it is more than 10 years ago I used a dfs3 file.

**Comment by mohm-dhi** [comment]
There are some projects that I am involved with that still work with Dfs2 (3D) and Dfs3 files. I already wrote a code to return the bottom  values. for the Dfs3 file so I can make a pull request later. for Dfsu file with all sigma layer the bottom value would be the first layer from the bottom but in case of z-sigma, it would be nice to have that function added to dfsu as well.

**Comment by jsmariegaard** [comment]
@ecomodeller does this now work dfs.read(layers="bottom") ?

**Comment by ecomodeller** [comment]
Yes, take a look at the new Dfs3 notebook.
![image](https://user-images.githubusercontent.com/614215/166147635-67182459-7af2-4775-a0cf-a9a103c5d0f2.png)

It is simply a rewrite of the `Dfs3.get_bottom_values` (created by @mohm-dhi) to make it consistent with Dfsu3d.
