### ISSUE TITLE
How to query gatelevel?

### ISSUE THREAD

**Issue by Wanjenzec** [DHI/mikeio#163]
Hi, I want to query a gate level of an orifice from a res1d file. How can this be accomplished?
Thank you!

**Comment by rhaDHI** [comment]
Hi @Wanjenzec,
You can query 'GateLevel' as a quantity in a reach. Checkout the Res1D notebook: https://github.com/DHI/mikeio/blob/master/notebooks/Res1D.ipynb
It also shows how to see all possible quantities you can extract and how.
