### ISSUE TITLE
not able to read 'PumpIsActive'

### ISSUE THREAD

**Issue by Wanjenzec** [DHI/mikeio#168]
If I run mike1d_quantities() I see there is an option to call 'PumpIsActive'

However when I run:
res1d = Res1D(resultfile)
res1d.quantities
I only see the following quantities:
['WaterLevel',
 'Discharge',
 'FlowVelocity',
 'DischargeInStructure',
 'ControlStrategyId',
 'CrestLevel',
 'GateLevel']

So how can I call 'PumpIsActive' ?

**Comment by rhaDHI** [comment]
mike1d_quantities gives you all possible quantities that exists in Mike1D. res1d.quantities will give you all that are present in your result data file. 'PumpIsActive'-quantity is not saved as part of your results. . You must add it to the result file specifications list in the Mike1DData object before simulating your model. Don't know how to do it from GUI = MIKE support question.
