### ISSUE TITLE
Write non-equidistant dfs2 files

### ISSUE THREAD

**Issue by rhaDHI** [DHI/mikeio#171]
Reintroduce writing of non-equidistant dfs2 files.

**Comment by rhaDHI** [comment]
I see that this PR: https://github.com/DHI/mikeio/pull/164 maybe solved this issue. Please do not close until this features has been pushed to a new pypi package.

**Comment by jsmariegaard** [comment]
> I see that this PR: #164 maybe solved this issue. Please do not close this issue until this feature has been pushed to a new pypi package.

Just out of curiosity, why do you want to wait until release? Is this good practice or is it just for this issue?

**Comment by rhaDHI** [comment]
A user asked about this feature so I opened and referred to this issue so we can track when the feature is available again in a versioned package.

**Comment by ecomodeller** [comment]
A new version of mikeio (0.6.2) is now available on [PyPI](https://pypi.org/project/mikeio/)
