### ISSUE TITLE
"Write Dfs2" Doesn't Write The Geographical Information Correctly 

### ISSUE THREAD

**Issue by mohm-dhi** [DHI/mikeio#180]
This bug can be repeated very easily with any dfs2 file. you can just read and try to write to another name. Now if you look at the new file geographical information, you can see the long lat were written in the easting and northing section. 

To solve this, easting and northing should be provided to coordinate list, but I cannot find a way to get them from the file. I just copied manually. Is there a way that we get the easting and northing information from the file? 
  
```python
from mikeio import Dfs2

new_file_name = "new_file.dfs2"
dfs = Dfs2("some_file.dfs2")
data = dfs.read()

coordinate = [dfs.projection_string, dfs.longitude, dfs.latitude, dfs.orientation]
dfs.write(filename=new_file_name,
          data=data.data,
          datetimes=data.time,
          coordinate=coordinate, dx=dfs.dx, dy=dfs.dy,
          items=dfs.items)
```

**Comment by mohm-dhi** [comment]
Well, I found this from the test that helped me, but still curious why the previous method shouldn't work :)

def test_write_modified_data_to_new_file(tmpdir):
    filename = r"tests/testdata/gebco_sound.dfs2"
    dfs = Dfs2(filename)
    outfilename = os.path.join(tmpdir.dirname, "mod.dfs2")
    ds = dfs.read()
    ds.data[0] = ds.data[0] + 10.0
    dfs.write(outfilename, ds)
    dfsmod = Dfs2(outfilename)
    assert dfs._longitude == dfsmod._longitude

**Comment by ecomodeller** [comment]
The reason the first version doesn't work is that when you explicitly supply coordinates and the projection string is not "LONG/LAT" the origin must be in projected coordinates (easting, northing) and not longitude, latitude.

If you don't supply the coordinates argument, the default is to use the same coordinates.
This is fed into `CreateProjectionProjOrigin` vs `CreateProjectionGeoOrigin`
https://github.com/DHI/mikeio/blob/7b66eeab807fd07be4847cae81331a22d3d46f5b/mikeio/dfs.py#L252-L258

If you have a suggestion on how to handle this in a better way, I am all ears:

As long as it is:
- Simple to specify geographical cooordinates
- Simple to specify projected cooordinates
- Simple to modify existing file

I know that @georgebv has something going on in #173, maybe this would help clarify this confusion.

**Comment by ecomodeller** [comment]
Would you like to give it a try by installing mikeio from the main branch?

See an example of creating Dfs2 in geographical and projected coordinates in the course book here:
https://dhi.github.io/getting-started-with-mikeio/dfs2.html

It would be great if we could close this.

**Comment by mohm-dhi** [comment]
Thanks Henrik,
You can close this branch.

Mohammad
