### ISSUE TITLE
Extract from DFS3 without reading entire file to memory?

### ISSUE THREAD

**Issue by spizwhiz** [DHI/mikeio#188]
Hello,

I would like to read a vertical cross section from a DFS3 file that is rather large ( >30GB).  The file is the 3DUZ.dfs3 from a MIKE SHE simulation.

When I try to use the dfs3.read_slice method, i get a memory error that suggests that the whole file is being read before it attempts to return the slice being requested, is that correct?

On another note, I am hoping to somehow plot the dfs3 vertical cross section in real space (meters below ground surface), rather than by cell number.  Is there any way to do this using mikeio (i think i would somehow need to also extract node locations and discretization to do this).

`MemoryError                               Traceback (most recent call last)
<ipython-input-11-a3e985a30d33> in <module>
      1 gd = dfs3.read_slice(r"D:\MIKE_SHE\Setup_GravD\Model_Test_4m_GridMET_lowK.she - Result Files\Model_Test_4m_GridMET_lowK_3DUZ.dfs3",
----> 2                     [0], [30,19],[110,19], layers = None, conservative = True)
      3 
      4 gd

~\anaconda3\lib\site-packages\mikeio\dfs3.py in read_slice(self, dfs3file, item_numbers, lower_left_xy, upper_right_xy, layers, conservative)
    105         """
    106 
--> 107         data = self.read(dfs3file, item_numbers, layers=layers)
    108 
    109         dfs = DfsFileFactory.DfsGenericOpen(dfs3file)

~\anaconda3\lib\site-packages\mikeio\dfs3.py in read(self, dfs3file, item_numbers, layers, coordinates)
    221                         # Initialize an empty data block
    222                         data = np.ndarray(
--> 223                             shape=(yNum, xNum, zNum, nt), dtype=float
    224                         )  # .fill(deleteValue)
    225                         data_list.append(data)

MemoryError: Unable to allocate 38.3 GiB for an array with shape (1030, 268, 137, 136) and data type float64`

**Comment by jsmariegaard** [comment]
@mohm-dhi I think you have a bit of experience with dfs3 files?

**Comment by mohm-dhi** [comment]
Yes, I already fixed this issue in the new version of mikeio. It can read each timestep or list of timesteps. So please get the new version.

**Comment by spizwhiz** [comment]
Thanks

With latest conda version (0.6.3), I get:

`TypeError                                 Traceback (most recent call last)
<ipython-input-29-72d927c3f443> in <module>
----> 1 gd = Dfs3.read(file,items=None, layers=None, coordinates=None, time_steps=None)

TypeError: read() got multiple values for argument 'items''`

I didn't have this error before, so I'm not sure what the issue may be.

**Comment by mohm-dhi** [comment]
well it seems like your code is not right! 
it should be something like this: 

from mikeio import Dfs3
file_name = "one_file_name.dfs3"

dfs = Dfs3(one_file_name.dfs3)

data = dfs.read(items=[0, 1], time_steps= [0,1,4,5])


The above code reads the first and second item of the file ate timesteps 0, 1, 4 , 5


you can put is in the loop as well. 

for i in range(dfs.n_timesteps):
    data = dfs.read(time_steps=[i])


this will read all the timesteps one by one

**Comment by spizwhiz** [comment]
Thanks!

As per the second part of my question, is there any way to reference the nodes to the correct position in vertical space so that they can be plotted in a x-z plane cross section, for example?

**Comment by mohm-dhi** [comment]
I think you just need to multiply the cell number by dz. In dfs3 files the information for the nodes and cells are not stored similar to what we have in dfsu files. so the depth would be 

depth = [i*dz for i in range(number_of_z_layer)]

**Comment by spizwhiz** [comment]
Perhaps I'm mis-understanding, but the code you give gets me a list of integers from 0 to number_of_z_layer, since dfs.dz = 1 for my .dfs3 file.  It seems like this is just a placeholder since I have variable grid spacing in the z-direction?

What I would expect (hope) is that dfs.dz would be some kind of array, but it sounds like that information just isn't in the .dfs3 file, is that correct?

Are you also saying there is currently no way to retrieve it (e.g. from other model files)?

If so, that is OK, and I'll move on.

Thanks

**Comment by ecomodeller** [comment]
I don't think it is possible to get this from a dfs3 file, but let's ask @marcridler who is more familiar with MIKE SHE.

**Comment by marcridler** [comment]
@spizwhiz & @ecomodeller 
If I understand your question - you'd like to retrieve and plot profiles of the 3d data (Saturated Zone for  example) given the different spatially varible comuational layers defined in the model. 
This isn't possible from just reading a dfs3 file. The thicknesses and distribution of the layers is contained in the mike model files, and not in the dfs3 file. The Dfs3 only contains the layer data and is 'dumb' with respect to the thickness and distribution of those layers. 
The only way I know to get these data is to open up the Result tab in MIKE Zero. From there you can select the result variable of interest, and then create slices using the GUI -> from which you get .REV files. 
Good luck.
Marc

**Comment by spizwhiz** [comment]
@marcridler @ecomodeller 

I guess I'm not sure about the procedure you mention (i.e., I wasn't able to figure out how to make slice with depth values instead of just the computational layers).  Do you mean open the .dfs3 file and use 2d profile from 3d grid utility?  When I do this the slice is still 'dumb' in that the spatial variation in thickness is not captured.

I was able to create what I wanted using a python script and mikeio, but it is pretty convoluted process as I have it now. 

I'm linking my script here in case anyone wants to improve on it and perhaps implement to the package.

https://drive.google.com/file/d/1p4sT2cA-pOxUEDk_ExoAzgANNVLdis9Z/view?usp=sharing

**Comment by mohm-dhi** [comment]
> dfs.dz = 1

Hi @spizwhiz 

Dfs3 file does not have variable grid size stored in the file. I think you can just get the vertical grid dz values from your model setup and create the depth vector. 

you can do something like this: (This is just an example !)
import numpy as np
import matplotlib.pyplot as plt

x = np.arange(0,20,2)
y= np.array([0, -2,-4,-8,-15, -30])    # this is your depth values that are variable grid spacing as you see

[X,Y] = np.meshgrid(x,y)

Data = X**2+Y**2    # this can be your sliced data 

plt.contourf(X,Y,Data , cmap='jet')

![image](https://user-images.githubusercontent.com/65772896/108913459-f99b2b80-75f7-11eb-8ff1-6fd9919bc3d3.png)

or 

plt.pcolor(X,Y,Data, cmap='jet')

![image](https://user-images.githubusercontent.com/65772896/108913537-1afc1780-75f8-11eb-80ca-15d8aab00378.png)


I hope that helps.

**Comment by spizwhiz** [comment]
Hi @mohm-dhi 

Yes, this is what I ended up doing in my script.

There is some other code in there to extract the depth vectors and put them in a 3d matrix by grid code also.

Thanks,
