### ISSUE TITLE
Generic processing of dfs files

### ISSUE THREAD

**Issue by ecomodeller** [DHI/mikeio#19]
Add functionality to process dfs irrespective of geometry

Examples:
- Scale: multiply all data in file with a scale factor
- AddConstant: add a constant to all data in the file
- Sum: add to files together (assuming identical structure)
- Diff: subtract to files from each other (assuming identical structure)

The requirement of identical structure could be relaxed if one of the files is static (i.e. only has a single timestep)

**Comment by jsmariegaard** [comment]
Maybe also concatenation of dfs files?

**Comment by ecomodeller** [comment]
First two points implemented.
https://github.com/DHI/mikeio/blob/2e1d203620558553f9bb8336301f437226cabb53/mikeio/generic.py#L9
