### ISSUE TITLE
getOpenFileName hangs when using mikeio

### ISSUE THREAD

**Issue by kagb-cowi** [DHI/mikeio#192]
The below snippet shows a problem in the mikeio python module. Disabling the first line helps the problem.
 
An error message appears: QWindowsContext: OleInitialize() failed:  "COM error 0xffffffff80010106 RPC_E_CHANGED_MODE (Unknown error 0x080010106)"
And the native getOpenFileName dialog appears, but won’t respond, leaving the application hanging.
 
Python 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)] on win32
I tried with the most recent Python 3.9, but mikeio is not available for this version yet.
mikeio==0.6.3
PySide2==5.15.2

```
import mikeio # This causes problems with the native getOpenFileName dialog
from PySide2 import QtWidgets
 
app = QtWidgets.QApplication()
form = QtWidgets.QDialog()
form.show()
#fileopen = QtWidgets.QFileDialog.getOpenFileName(form, "Test", options=QtWidgets.QFileDialog.DontUseNativeDialog)
fileopen = QtWidgets.QFileDialog.getOpenFileName(form, "Test")
print(fileopen)
```

**Comment by ecomodeller** [comment]
Sorry, but I am not sure we have anyone in the MIKEIO community that have experience with Qt applications.

Maybe @red5alex knows?

**Comment by red5alex** [comment]
Not to that technical depth … EDSO might help.

**Comment by kagb-cowi** [comment]
I figured out that the issue comes from importing the clr module (substituting mikeio with clr in the above snippet is the same). I will keep looking into this.

**Comment by kagb-cowi** [comment]
Found a workaround. I got the solution from this thread:
https://stackoverflow.com/questions/20525554/pyside-qt-could-not-initialize-ole-error-80010106

Insert the two lines before import mikeio (or import clr):
```
import pythoncom
pythoncom.CoInitialize()
import mikeio
```

**Comment by dkvg3** [comment]
Reading Dfs3 file by mikeio is taking longer time to read (Approx. 7 min)
ds = Dfs3(filename)
dfs = ds.read()

**Comment by jsmariegaard** [comment]
Hi @dkvg3, you're adding your comment about Dfs3 in a closed issue about Qt applications and .NET. That does not seem related - could you please open a new issue? And please also add information about the size of your file and version of MIKE IO. Thanks
