### ISSUE TITLE
dfs2 export of ERA5 data for Precipitation/Evaporation rates

### ISSUE THREAD

**Issue by AlekseiBuinyi** [DHI/mikeio#199]
@ecomodeller 

I've got a question.

I've used mikeio for resaving NetCDF into dfs2 - and did it successfully for air pressure, wind, temperature, radiation fluxes, and sea ice cover, but not for the Mean Total Precipitation Rate and Mean Evaporation Rate. 
I've got an answer:

'Argument exception: Item and unit is not compatible
   в DHI.Generic.MikeZero.eumQuantity..ctor(eumItem item, eumUnit unit)
   в DHI.Generic.MikeZero.DFS.DfsSimpleItemInfo..ctor(IDfsDynamicItemInfo itemInfo)
   в DHI.Generic.MikeZero.DFS.DfsItemInfo..ctor(IDfsDynamicItemInfo itemInfo)
   в DHI.Generic.MikeZero.DFS.DfsDynamicItemInfo..ctor(IDfsDynamicItemInfo dynamicItemInfo)
   в DHI.Generic.MikeZero.DFS.DfsDynamicItemBuilder.GetDynamicItemInfo()
   в DHI.Generic.MikeZero.DFS.dfs123.Dfs123Builder.CreateBuilder()
   в DHI.Generic.MikeZero.DFS.dfs123.Dfs123Builder.CreateFile(String filename)`

I use an example of the script written in the notebook, but the answer is also here...

`# Mean Evaporation rate export
EUMType.Evaporation_Rate
EUMUnit.kg_meter_pow_2_per_sec
from mikeio import Dfs2
from mikeio.eum import ItemInfo
d = [mer]
coordinate = ['LONG/LAT', x0, y0, 0]
items = [ItemInfo("Mean Evaporation Rate", EUMType.Evaporation_Rate, EUMUnit.kg_meter_pow_2_per_sec)]

dfs = Dfs2()
dfs.write(filename='mer_era5_ma_2021.dfs2',
           data=d,
           dt=3600,
           start_time = start_time,
           coordinate=coordinate, dx=dx, dy=dy,
           items=items
)`

Is there any idea why it doesn't work?

**Comment by mnaseeft** [comment]
Hi  AlekseiBuinyi,
I'm trying to include Sea ice coverage input for my sw model. How did you created the dfs2 file for ice coverage? how did you specified the EUMUnit and EUNType for ice cover?
