### ISSUE TITLE
Improve handling of res1d files

### ISSUE THREAD

**Issue by ecomodeller** [DHI/mikeio#20]
- As similar as possible to other classes
- Additional functionality

**Comment by rhaDHI** [comment]
I tried to fix the first point and pulled requested the changes in PR #22 . Cannot assign an issue. Maybe I don't have high enough rights within this repo?

**Comment by rhaDHI** [comment]
I think there is a lot of functionality that can be added more easily if we wrap the DHI.Services.Providers.Mike1D package. It is available from our internal nuget packages and is internal open source. Then you also don't depend on your own MIKE installation. But I guess it requires some nuget package handling.

**Comment by ecomodeller** [comment]
It has to be available for anyone (not only internal) in order to be used in mikeio, since this is a public repo.

4 mars 2020 kl. 15:46 skrev Rasmus Halvgaard <notifications@github.com>:

﻿

I think there is a lot of functionality that can be added more easily if we wrap the DHI.Services.Providers.Mike1D package. It is available from our internal nuget packages and is internal open source. Then you also don't depend on your own MIKE installation. But I guess it requires some nuget package handling.

**Comment by rhaDHI** [comment]
@larsmichael Will this Domain Service Provider be available at some point on public nuget?

**Comment by rhaDHI** [comment]
> It has to be available for anyone (not only internal) in order to be used in mikeio, since this is a public repo.

Can't we just add the dll's from the provider nuget package to the mikeio package?

**Comment by ecomodeller** [comment]
Only if the license of that package permits that.

**Comment by ecomodeller** [comment]
@rhaDHI Should we close this?

**Comment by rhaDHI** [comment]
Yeah, we need Domain Services to be released publicly. I don't want to re-code the functionality in a new language.

**Comment by larsmichael** [comment]
I am regularly advocating to make the DS GitHub repositories public, but apparently the organization is not yet mature enough to agree on this. But I will continue to advocate this.

**Comment by JesperGr** [comment]
The DHI.Services.Providers.Mike1D is a fairly simple wrapper of the MIKE 1D ResultData object, implementing the DHI.Services interfaces. There is not really a lot of functionality in the DHI.Services.Providers.Mike1D - the power is only really released when the entire DHI.Services is unleashed. So, unless to use the DHI.Services for all mikeio files, I think there is no need to to just use it for MIKE 1D? 

If there is some functionality in DHI.Services.Providers.Mike1D that would be really nice to utilize from Python, and if it is not directly depending on the DHI.Services, do let me know, and it could potentially go directly into the MIKE 1D ResultData library.

**Comment by rhaDHI** [comment]
It still requires working more extensively with C# classes from python which is a bit more cumbersome without Linq and other convenient C# language notation + maintenance.
I did add string query functionality so it is easier to extract data from matlab or python, e.g. chainage-number-free extraction = "reach_id; quantity; from" to get the HD point closest to the reach from node without knowing chainge-number or "reach_id; "WaterVolume"; sum" to get the total volume in the reach by summing all HD points, or parsing quantities as strings in these queries instead of classes or enums.

But maybe we can add this string query functionality to DHI.Mike1D.ResultDataAccess to make it more python/matlab friendly? @JesperGr

**Comment by JesperGr** [comment]
We could add a ResultDataQuery class to MIKE 1D that does that. Is the query string very important, or could it just be a class with a number of methods on the form:

double GetValue(string reachId, string quantityId, string endNodeId)

to be called like:

resultDataQuery.GetValue("reach_id", "WaterLevel", "startNode")

? 

Reason for asking is that query strings are difficult to document and maintain, and then we are to assure compatibility between DHI.Services strings and MIKE 1D, which is also not optimal

**Comment by JesperGr** [comment]
By the way, the ResultDataExtract does also this:

https://github.com/DHI/Mike1D-SDK-examples/blob/master/scripts/ResultDataExtract.py

Major difference is probably that the ResultDataExtract is meant as a command line extraction tool, and not as a library method. But that could probably be combined in the mikeio python library? I would be happy to see the ResultDataExtract merge into the mikeio...

**Comment by rhaDHI** [comment]
1) Does not need to be a string, but then you need to call separate query classes for nodes, reaches, catchments as the id's could be the same. Anyway, what is the timeline for adding this functionality? I guess Mike1D is not internal open source yet.

2) Yeah, that script seems like an obvious candidate for mikeio. If we handle 1) first, then that script could the usage example.

**Comment by JesperGr** [comment]
1. You are right, I would probably do a different method for nodes, reaches and catchments. Timeline would be 2021 release, so do it over the summer.

I guess you have access to DevOps? Can you get to:
https://dev.azure.com/dhigroup/MIKE%20test%20pilot/_git/Mike1D

?

We could make a branch there for code sharing and "internal open source"-like activities for stuff like this.

**Comment by rhaDHI** [comment]
I have access to DevOps but not to that project. I requested access. Let me know if you start a branch with this feature and then I might be able to help.

**Comment by rhaDHI** [comment]
I have access now and can sync repo.

**Comment by JesperGr** [comment]
There is now a branch called in the MIKE 1D git repository
    feature/ResultDataQuery
In the ResultData project, there is a new ResultDataQuery.cs and in the unit test project there is a ResultDataQueryTest.cs for unit testing. 

I already added a few methods, but otherwise you are free to go :-)

**Comment by rhaDHI** [comment]
Nice thanks.
Where do I get reference to DHI.Mike1D.Generic and which version? Is MathUtil part of that (is also missing)?

**Comment by JesperGr** [comment]
DHI.Mike1D.Generic is part of the entire Mike1D solution, and in the DHI.Mike1D.ResultDataAccess, it is a project reference.

**Comment by rhaDHI** [comment]
Hmm.. I cannot compile DHI.Mike1D.Generic using Mike1D.sln. Many references are missing including DHI.Generic(.MikeZero) and DHI.projections.

**Comment by JesperGr** [comment]
Yes, you will need a number of dependencies from \\devdk\f\latest\bin\x64

The "developer" approach is to copy over that folder to c:\work\main\Products\bin\x64, and then setup Visual Studio to look for dependencies in that folder.

**Comment by rhaDHI** [comment]
I don't have access to the f drive. I tried getting access a few years ago, but was very aggressively turned down. Any other "internal open source"-friendly way?

**Comment by rhaDHI** [comment]
We implemented some of the desired res1d functionality in Mike1D.
@JesperGr When do you expect to commit the changes in a public Mike1D nuget package?

**Comment by JesperGr** [comment]
Release 2020 Update 1 has just been finalized. Next public release is Release 2021 in late November, so officially that is the time. If depending on the MIKE SDK, this is the only option. 

For NuGet, we can push some pre-releases to our internal NuGet feeds earlier, and then those files could be deployed with MikeIO. That could potentially be in a months time.

**Comment by rhaDHI** [comment]
OK. Sounds good with the pre-released nuget packages. Then there should be time to test it and wrap it in MikeIO before release in november.
