### ISSUE TITLE
Problem with dfs2 export of kg_meter_pow_2_per_sec units

### ISSUE THREAD

**Issue by AlekseiBuinyi** [DHI/mikeio#200]
**Describe the bug**
I've got the Evaporation rate and Precipitation rate obtained from ERA 5 reanalysis. They are written in kg m-2 s-1 units. When I try to resave them from .nc to .dfs2 I face a problem.

'ArgumentException: Item and unit is not compatible
   в DHI.Generic.MikeZero.eumQuantity..ctor(eumItem item, eumUnit unit)
   в DHI.Generic.MikeZero.DFS.DfsSimpleItemInfo..ctor(IDfsDynamicItemInfo itemInfo)
   в DHI.Generic.MikeZero.DFS.DfsItemInfo..ctor(IDfsDynamicItemInfo itemInfo)
   в DHI.Generic.MikeZero.DFS.DfsDynamicItemInfo..ctor(IDfsDynamicItemInfo dynamicItemInfo)
   в DHI.Generic.MikeZero.DFS.DfsDynamicItemBuilder.GetDynamicItemInfo()
   в DHI.Generic.MikeZero.DFS.dfs123.Dfs123Builder.CreateBuilder()
   в DHI.Generic.MikeZero.DFS.dfs123.Dfs123Builder.CreateFile(String filename)'

As I understand, the problem is: the unit is non-applicable for such type of data, because there are no problems with, e.g. mm_per_day units. Is it possible to get some advice on such a type of data?
  
**To Reproduce**

`from mikeio import Dfs2
from mikeio.eum import ItemInfo
d = [mtpr]
coordinate = ['LONG/LAT', x0, y0, 0]
items = [ItemInfo("Mean Total Precipitation Rate", EUMType.Precipitation_Rate, EUMUnit.kg_meter_pow_2_per_sec)]
dfs = Dfs2()
dfs.write(filename='mtpr_era5_ma_2021_1.dfs2',
           data=d,
           dt=3600,
           start_time = start_time,
           coordinate=coordinate, dx=dx, dy=dy,
           items=items
)`

**Expected behavior**
I'd like to get a dfs2 file with my forcing for Mike21.  

**Screenshots**
![image](https://user-images.githubusercontent.com/44070646/115245074-39305080-a12d-11eb-907e-55249d35900f.png)

**System information:**
 - Python 3.8
 - Mike Zero Release 2021

**Comment by ecomodeller** [comment]
The limitation of which variables and units that are applicable can be found by looking at the units like this:

![image](https://user-images.githubusercontent.com/614215/115246554-46960c80-a126-11eb-8249-719654af2d45.png)

I expect it doesn't make sense to use the native units in a dfs2 because the MIKE model will not accept it as input.

**Comment by AlekseiBuinyi** [comment]
> The limitation of which variables and units that are applicable can be found by looking at the units like this:
> 
> ![image](https://user-images.githubusercontent.com/614215/115246554-46960c80-a126-11eb-8249-719654af2d45.png)
> 
> I expect it doesn't make sense to use the native units in a dfs2 because the MIKE model will not accept it as input.

OK,
Does it mean your options are the only readable by Mike and I have just to convert them?

**Comment by ecomodeller** [comment]
I think so, but you can check with MIKE support to be sure.

**Comment by AlekseiBuinyi** [comment]
> I think so, but you can check with MIKE support to be sure.

ok, thank you
