### ISSUE TITLE
dfs3 irregular depth grid... is it possible?

### ISSUE THREAD

**Issue by AlekseiBuinyi** [DHI/mikeio#204]
I've got a question: is it possible to make a dfs3 file with irregular depth part? I've made a part of script to write dfs3 variable, but it doesn't contain the depth variable as I need it (dz in this case changes from 5m at the surface to 25m at the depth of 300m). Is it any idea how to make it?

`
''' Temperature export '''
d = [to]
coordinate = ['LONG/LAT', x0, y0, 0]
dfs = Dfs3()
dfs.write(filename='t3m_2010-2019.dfs3',
           data=d,
           #timeseries_unit=TimeStep.SECOND,
           dt=dt,
           start_time = start_time, 
           coordinate=coordinate, dx=dx, dy=dy,
           title="Temperature 3d",
           items=[ItemInfo("Temperature", EUMType.Temperature, EUMUnit.degree_Celsius)]
)
`

One more question: 

timeseries_unit=TimeStep.SECOND line doesn't work. Why?

**Comment by ecomodeller** [comment]
It is not possible to have non-equidistant spatial axes in dfs1,2,3.

The default timeseries unit is second.

**Comment by AlekseiBuinyi** [comment]
ok, thank you.
