### ISSUE TITLE
skipping of warm up with concat not possible

### ISSUE THREAD

**Issue by Hendrik1987** [DHI/mikeio#205]
https://github.com/DHI/mikeio/blob/ed60b7caeb1e2a2003266a69607157f2f3302c20/mikeio/generic.py#L244

Wouldn't it be better to keep the end of the first and skip the beginning of the latter file in order to skip spin-up periods?

This can currently not be achieved as no option is available and the files have to be in chronological order.

**Comment by ecomodeller** [comment]
> Wouldn't it be better...

No, I don't think so. 

Imagine that you are running a 24h forecast every hour and want to concatenate the results to a combined dataset.

Spin-up problems are avoided by using appropriate initial conditions.

But I am not opposed to having the option, so feel free to create a Pull Request 😉 

```
def concat(infilenames: List[str], outfilename: str, overwrite_with_latest=True) -> None:

...
```

**Comment by Hendrik1987** [comment]
Fair point, I guess that's the hindcast vs. forecast point of view... :-)
