### ISSUE TITLE
dfs0 read units

### ISSUE THREAD

**Issue by lizaclark** [DHI/mikeio#21]
I frequently use the dfs0 functions to read in dfs0 files for data analysis. Sometimes this requires comparing with data in different units. Since dfs0 files used by DHI include unit information, I think it would be helpful to either extract these with `dfs0.read()` or to include that option in a separate function. 

It could be something around [lines 36-38 in dfs0.py](https://github.com/DHI/mikeio/blob/ab7131d766a2ee134dbb5c955465580bdaa579d4/mikeio/dfs0.py#L36) along the lines of:
```python
units = []
names = []
for i in range(n_items):
    names.append(dfs.ItemInfo[i].Name)
    units.append(dfs.ItemInfo[i].Quantity.UnitAbbreviation)
```
Then `units` would be passed into and out of `read()` and into (but not out of?) `read_to_pandas()`

I am happy to develop a pull request with changes along these lines unless there is a reason that this information is not currently extracted.

**Comment by ecomodeller** [comment]
There is no reason that units are not included in the read() methods, except priority, so please go ahead!

**Comment by ecomodeller** [comment]
Types and units are now read along with the names.
