### ISSUE TITLE
pip install mikeio still requires pythonnet

### ISSUE THREAD

**Issue by bhlevca** [DHI/mikeio#213]
**Describe the bug**
`pip install mikeio ` - fails on Linux due to _pythonnet_ dependency

 while

` pip3 install https://github.com/DHI/mikeio/archive/main.zip` -installs just fine

**To Reproduce**
run `pip install mikeio ` on Linux without pythonnet installed

**System information:**
 - Python version: 3.8
 - MIKE version: latest

**Comment by jsmariegaard** [comment]
The .NET-free version of mikeio have not yet been released to pypi. That's why the development version runs on Linux and the pypi version doesn't :-)
