### ISSUE TITLE
Unable to create dfs2 file with dimensionless items like sea ice concentration

### ISSUE THREAD

**Issue by mnaseeft** [DHI/mikeio#219]
I'm trying to include ice coverage file (dfs2) for my MIKE21 SW model. it's a dimensionless factor ranging from 0 to 1. I have successfully created the dfs2 file using mikeio by without adding "EUMUnit" in items (otherwise getting error) [figure1 jupyter]. BUT, I can not include this file in MIKE21 SW set up. it showing  X mark for "Item type=Dimensionless factor" in "Constraints info" [figure2 sw].  How to specify the dimensionless factor in "EUMUnit"? Is there any list for available EUMUnit?

`from mikeio import Dfs2
from mikeio.eum import ItemInfo
dfsfilename = "SeaIce_2017.dfs2"

coordinate = ['LONG/LAT', x0, y0, 0]
d=[ci]
dfs = Dfs2()
dfs.write(filename=dfsfilename,
           data=d,
           dt=21600,
           start_time = start_time, 
           coordinate=coordinate, dx=dx, dy=dy,
           items=[ItemInfo("Sea Ice concentration", EUMType.Ice_concentration)]
)`

![sw](https://user-images.githubusercontent.com/89463903/130629076-98853772-0cf1-4364-90b5-b6b73c078299.png)
![jupyter](https://user-images.githubusercontent.com/89463903/130629094-0d1146b2-e221-4b6f-a238-4701f8ce7ff0.png)

**System information:**
 - Python version: Python 3.8.5 
 - MIKE version: 2019

**Comment by ecomodeller** [comment]
MIKE 21 SW expects a dfs2 file with the EUM type Dimensionless factor and not Ice concentration

This will work:
```
ItemInfo("Sea Ice concentration", EUMType.Dimensionless_factor)
```

**Comment by mnaseeft** [comment]
Thank you so much... it worked!
