### ISSUE TITLE
How to add variable and unit to dfs0

### ISSUE THREAD

**Issue by amit1304in1** [DHI/mikeio#242]
Hello,

I am converting a csv file in dfs0. I want to add variable and unit for dfs0. How to pass unit and variable in df.todfs0

**Comment by jsmariegaard** [comment]
By using the items or itemtype argument, e.g.: 

    from mikeio.eum import EUMType
    df.to_dfs0("data_eum.dfs0", itemtype=EUMType.Temperature)

From the docstring:

    Create a dfs0
    Parameters
    ----------
    filename: str
        filename to write output
    itemtype: EUMType, optional
        Same type for all items
    unit: EUMUnit, optional
        Same unit for all items
    items: list[ItemInfo]
        Different types, units for each items, similar to `create`
    title: str, optional
        Title of dfs0 file
    dtype : np.dtype, optional
            default np.float32
