### ISSUE TITLE
Concatenation options

### ISSUE THREAD

**Issue by ecomodeller** [DHI/mikeio#273]
Concatenation in time is possible using either `Dataset.concat`
https://github.com/DHI/mikeio/blob/2acbdb48575b6ca477ea59ba7205eb1174fc97b9/mikeio/dataset.py#L484
or `generic.concat`
https://github.com/DHI/mikeio/blob/2acbdb48575b6ca477ea59ba7205eb1174fc97b9/mikeio/generic.py#L301

In case of overlapping time-series, the last data will overwrite the old data, since duplicate timesteps is usually not what we want in the end.

It would be useful to have more options how this concatenation should be performed.

E.g. to be able to select if the old or the new data will win, as illustrated in this example from two overlapping forecasts.
![image](https://user-images.githubusercontent.com/614215/148198242-58628ea1-d646-4c43-94b0-5f660d2fa1dd.png)
![image](https://user-images.githubusercontent.com/614215/148198274-a287635e-5461-4c2b-a6f5-a4b7a57c16a9.png)

**Comment by jsmariegaard** [comment]
Closed by #276
