### ISSUE TITLE
Dfs2 file read and write is different in development and release version

### ISSUE THREAD

**Issue by mohm-dhi** [DHI/mikeio#275]
I was working on adding a new feature to Dfs2 read function to be able to read only a subset of the data that I realized that this test method produce a different result using when it is executed in development version compared to released version. So strange :-) 

def test_write_modified_data_to_new_file(dfs2_gebco, tmpdir):
    dfs = dfs2_gebco
    outfilename = os.path.join(tmpdir.dirname, "mod.dfs2")
    ds = dfs.read()
    ds.data[0] = ds.data[0] + 10.0
    dfs.write(outfilename, ds)
    dfsmod = Dfs2(outfilename)
    assert dfs._longitude == dfsmod._longitude

The test method by itself is misleading because it modifies the data but it checks the longitude instead. The better and more comprehensive test would be something like this: 

def test_write_modified_data_to_new_file(dfs2_gebco, tmpdir):
    dfs = dfs2_gebco
    outfilename = os.path.join(tmpdir.dirname, "mod.dfs2")
    ds = dfs.read()
    ds2 = ds.copy()
    ds2.data[0] = ds2.data[0] + 10.0
    dfs.write(outfilename, ds2.flipud())
    dfsmod = Dfs2(outfilename)
    dsmod = dfsmod.read()
    assert dfs._longitude == dfsmod._longitude
    assert ds.data[0][0, 0, 0] == dsmod.data[0][0, 0, 0] - 10
    assert ds.data[1][0, 0, 0] == dsmod.data[1][0, 0, 0]

It should be noted that I modified the dfs2 file to have two items instead of one, to make sure when we modify an item it does not impact other items. That as you noticed we should use flipud method on the dataset to make it right. But in the released version the flipud is not required and it made a lots of confusion for me. 

I could not figured out what happened to the released version or what is the difference between dev and released version that caused this issue. 

I would be available for further discussion about this, just please give me a call in Microsoft Teams. 

Thanks, 
Mohammad

**Comment by ecomodeller** [comment]
Great that you are looking into reading a subset of a Dfs2, that is on my wish list as well!

If you read a subset then the geometry on the Dfs2 object will differ from the one on the dataset and finding elements based on coordinates will be confusing 🤔 

This is one of the reasons we are doing some major overhaul in the [dataarray](https://github.com/DHI/mikeio/tree/dataarray), where we will add geographical information to the Dataset (and many other things). 

************************************************************************************************

1. Reading and writing data, should be symmetric, i.e. it should not be necessary to flip the data if you read it from a Dfs2 file.
2. Which released version are you referring to?
3. Yes, the test should have better assert statements 😉

**Comment by mohm-dhi** [comment]
Thank for your explanations. Yes, it is not very straight forward to extract a subset of the data, The feature is already exist in MIKE Zero Tools using transformation->Rotate Grid, I am not sure if that can help you to implement the feature in python as well. 

the released version was 0.11.1 

the  released version looks good, it does not require to do flipud but could you try in dev environment if that is the case too. I mean if you run that test you should be able to see the results and see if the result file is flipped. 

I have dev version on my laptop but I installed released version in one of the model machines. That was where I find out the difference, the code that I wrote and prepared on my laptop gives me flipped results on that machine.

**Comment by ecomodeller** [comment]
Sure, I used the Rotate Grid tool a lot many years ago when I was doing MIKE 3 Classic. I am sure we can get the same and better functionality in Python, e.g. to extract a subset which fits your modelling domain, without bringing out your pocket calculator.
