### ISSUE TITLE
How can I use functions from DHI.Mike1D.CrossSectionModule to convert txt file to xns11 file

### ISSUE THREAD

**Issue by lj512lj512** [DHI/mikeio#277]
**Describe the bug**
The cross-section properties can be exported to text files in MIKE Zero, I can also import the text files to MIKE Zero. The question is can I convert the exported txt file to an xns11 file using methods in MIKE 1D python API, like DHI.Mike1D.CrossSectionModule.

**To Reproduce**

Include code snippet

**Expected behavior**

**Screenshots**

**System information:**
 - Python version: 3.7
 - MIKE version: 2019

**Comment by ecomodeller** [comment]
From the Readme. "For res1d and xns11 files use the related package MIKE IO 1D"
