### ISSUE TITLE
Create dfs0 from pandas dataframe

### ISSUE THREAD

**Issue by ecomodeller** [DHI/mikeio#28]
Should be simple

**Comment by ecomodeller** [comment]
Use datetimeindex to determine if timeseries is equidistant.
In many cases data all columns in a dataframe will have the same types/units.

**Comment by jsmariegaard** [comment]
Does a df need to have a string as column "name" - could it be an object? EUM-object?

**Comment by ecomodeller** [comment]
It seems that you can have an object as column name, but then indexing into the dataframe with a string is not possible.

**Comment by ecomodeller** [comment]
Done
