### ISSUE TITLE
Large dfs2 files - do they always need to be read as float64?

### ISSUE THREAD

**Issue by murray91** [DHI/mikeio#281]
Hi!

Sometimes I work with large dfs2 files where memory becomes an issue. It would be nice to have the option to read data in as float32 to half the memory. It's pretty rare that I actually need float64 precision compared to float32.

**Comment by ecomodeller** [comment]
You are right, and we have this option for Dfsu files https://github.com/DHI/mikeio/blob/82760a899f4294bdddab6a0eb18f34b0754b21e0/mikeio/dfsu.py#L2160

We should add the same option to Dfs2, agree @jsmariegaard ?

**Comment by ecomodeller** [comment]
This option has now been released
```$ pip install --upgrade mikeio```

So now you should be able to use single precision 🚀,  and as added benefit you also get a warning ⚠️  that things are about to get a little different in the upcoming release 1.0. 

```python
>>> from mikeio import Dfs2
>>> import numpy as np
>>> dfs = Dfs2("random.dfs2", dtype=np.float32)
>>> ds = dfs.read()
>>> ds
<mikeio.Dataset>
Dimensions: (3, 100, 2)
Time: 2012-01-01 00:00:00 - 2012-01-01 00:00:24
Items:
  0:  testing water level <Water Level> (meter)
>>> ds[0].dtype
c:\users\jan\code\mikeio\mikeio\dataset.py:258: UserWarning: Indexing in MIKE IO 1.0 will not return a numpy array, but a mikeio.DataArray. More info: https://github.com/DHI/mikeio#readme
  warnings.warn(
dtype('float32')
```
