### ISSUE TITLE
DFSU - mikeio.DataArray fails when run interp() function

### ISSUE THREAD

**Issue by tuannvapj** [DHI/mikeio#291]
hi, 
i'm try example Dfsu - 2D interpolation from folder https://github.com/DHI/mikeio/tree/main/notebooks
When i run to the line using function interpolate, i get the error as show image.
<img width="1118" alt="Screen Shot 2022-03-15 at 22 19 26" src="https://user-images.githubusercontent.com/34207024/158410997-d10940b1-6532-4f8f-bca8-c8fdcc450f9a.png">

Look forward to the help!

System information:
python 3.7.12
mikeio 1.a1

**Comment by jsmariegaard** [comment]
Thanks for reporting. I can confirm that there is a problem with this interpolation functionality and we will look into it. We have not yet been through all the notebooks and are working to update them all in #287 :-)

**Comment by ecomodeller** [comment]
How about?
```
da.interp_like(g)
```

**Comment by jsmariegaard** [comment]
That does not work yet either - I tested this yesterday
