### ISSUE TITLE
Delete Value to NaN conversion not working

### ISSUE THREAD

**Issue by jsmariegaard** [DHI/mikeio#30]
I found that the following does not work:

        data[data == -1.0000000180025095e-35] = np.nan
        data[data == -1.0000000031710769e-30] = np.nan
        data[data == dfs.FileInfo.DeleteValueFloat] = np.nan
        data[data == dfs.FileInfo.DeleteValueDouble] = np.nan

maybe we should do this instead: 

        tol = 1e-3*abs(dfs.FileInfo.DeleteValueFloat)
        data[abs(data-dfs.FileInfo.DeleteValueFloat)<tol] = np.nan

And it's not very pretty to test for 4 different delete values. Hmmm. But it may still be a good idea.

**Comment by rhaDHI** [comment]
Use numpy.ma.masked_values() ?

**Comment by rhaDHI** [comment]
This issue has been fixed in recent PRs. Or is it still an issue @jsmariegaard @ecomodeller ?

**Comment by ecomodeller** [comment]
Not that I am aware of.

**Comment by jsmariegaard** [comment]
don't think so - just close
