### ISSUE TITLE
Adding netcdf to the test data

### ISSUE THREAD

**Issue by saberraz** [DHI/mikeio#31]
So that we can implement the format in QGIS/MDAL:
https://github.com/lutraconsulting/MDAL/issues/146
https://github.com/lutraconsulting/MDAL/issues/78

**Comment by ecomodeller** [comment]
You have to be a bit more specific. Do you want to import or export data to/from netcdf?

**Comment by saberraz** [comment]
We want to parse the netcdf format through MDAL library. Once MDAL parses the data, users can work with your [format in QGIS](https://docs.qgis.org/3.4/en/docs/user_manual/working_with_mesh/mesh_properties.html)

We are trying to avoid your SDK :)

**Comment by ecomodeller** [comment]
This package relies on the SDK see https://github.com/DHI/mikeio#requirements, so you will need that anyway. MIKE format is not based on netcdf. Is is still relevant?

**Comment by saberraz** [comment]
What we are really after is a netcdf format converted from your dfs2 file. We are not going to implement dfs2 format in MDAL. 

The ticket is simply a request for you to include the equivalent of netcdf formats of your files inside the testdata https://github.com/DHI/mikeio/tree/master/tests/testdata
especifcally: eq.dfs2, Grid1.dfs3 and random.dfs2

**Comment by jsmariegaard** [comment]
@saberraz is this still an issue? Or should we close this feature request?

**Comment by ecomodeller** [comment]
Closing stale issue
