### ISSUE TITLE
Import error (typo?)

### ISSUE THREAD

**Issue by spizwhiz** [DHI/mikeio#32]
I get the following error when importing:

> Traceback (most recent call last):

>   File "C:\Users\Spencer\Anaconda2\envs\py36\lib\site-packages\IPython\core\interactiveshell.py", line 2910, in run_code
>     exec(code_obj, self.user_global_ns, self.user_ns)
> 
>   File "<ipython-input-5-a63d527bbec8>", line 1, in <module>
>     import mikeio
> 
>   File "C:\Users\Spencer\Anaconda2\envs\py36\lib\site-packages\mikeio\__init__.py", line 65
>     raise Exception(f"{ext} is an unsupported extension")
>                                                        ^
> SyntaxError: invalid syntax

I believe that the 'f' in the exception is probably meant to be an 'r'

When I make this change, the library imports properly until the following:

> FileNotFoundException                     Traceback (most recent call last)
> <ipython-input-6-a63d527bbec8> in <module>()
> ----> 1 import mikeio
> 
> ~\Anaconda2\envs\py36\lib\site-packages\mikeio\__init__.py in <module>()
>       7 sys.path.append(r"C:\Program Files (x86)\DHI\2019\bin\x64")
>       8 sys.path.append(r"C:\Program Files (x86)\DHI\2020\bin\x64")
> ----> 9 clr.AddReference("DHI.Generic.MikeZero.DFS")
>      10 clr.AddReference("DHI.Generic.MikeZero.EUM")
>      11 clr.AddReference("System")
> 
> FileNotFoundException: Unable to find assembly 'DHI.Generic.MikeZero.DFS'.
>    at Python.Runtime.CLRModule.AddReference(String name)

I am using MIKE 2017, would that be the issue? Is this package only compatible with >2019 MIKE? (Tried modifying the 2019 append to path with 2017, and did not work).

Thanks

**Comment by jsmariegaard** [comment]
Is the assembly DHI.Generic.MikeZero.DFS in the folder that you have appended to the path C:\Program Files (x86)\DHI\2017\bin\x64 ?

**Comment by jsmariegaard** [comment]
And also the 'f' is not an error. 

"Also called “formatted string literals,” f-strings are string literals that have an f at the beginning and curly braces containing expressions that will be replaced with their values. The expressions are evaluated at runtime and then formatted using the __format__ protocol." - introduced in Python 3.6

**Comment by spizwhiz** [comment]
I cannot find DHI.Generic.MikeZero.DFS assembly. 

Can I get it somewhere?

Thanks

**Comment by spizwhiz** [comment]
Also, strange that the formatted string literal raised a syntax error since I was running in a python 3.6 environment.

**Comment by jsmariegaard** [comment]
Agree - I noticed also that you are using python 3.6 from your error messages. mikeio haven't been tested on old MIKE versions, but it may work if get the assemblies required - try the 2017 version of the SDK https://www.mikepoweredbydhi.com/download/mike-2017-sp2/mike-sdk?ref=%7B40160C10-5509-4460-A36F-FA2759EAC02F%7D

**Comment by jsmariegaard** [comment]
But I would strongly recommend to update MIKE to 2020 :-)

**Comment by ecomodeller** [comment]
For MIKE 2017 you need to install the MIKE SDK to get the DHI.Generic.MikeZero.DFS assembly.

This is from a test I just made on a server which only has the MIKE 2017 SDK installed, nothing else from MIKE.

Note that you have to add the correct path to the dfs assembly.
```
C:\Users\blue>python
Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.path.append(r"C:\Program Files (x86)\DHI\2017\MIKE SDK\bin")
>>> import mikeio
>>> ds = mikeio.read("c:/Users/blue/Desktop/random.dfs0")
>>> ds
DataSet(data, time, names)
Number of items: 2
Shape: (1000,)
2017-01-01 00:00:00 - 2017-07-28 03:00:00
>>>
```

**Comment by spizwhiz** [comment]
Thanks @ecomodeller !  This worked fine after sorting through some environment issues (ugh).
