### ISSUE TITLE
 Converting publicly available raster data to dfsu

### ISSUE THREAD

**Issue by robindang0573** [DHI/mikeio#34]
Dear Sir,
Can you show how to convert publicly available raster data to dfsu. Thanks

**Comment by ecomodeller** [comment]
Dfsu is a for unstructured mesh, not for raster data.

Have you looked at this [notebook](https://github.com/DHI/mikeio/blob/master/notebooks/Dfs2%20-%20Sea%20surface%20temperature.ipynb) for conversion of raster data to dfs2?

**Comment by robindang0573** [comment]
> Dfsu is a file format for unstructured mesh data, not for raster data.
> 
> Have you looked at this [notebook](https://github.com/DHI/mikeio/blob/master/notebooks/Dfs2%20-%20Sea%20surface%20temperature.ipynb) for conversion of raster data to dfs2?

Yep, I have read your notebook for conversion of raster to dfs2. I have used to MIKE 21 FM to model   my problem. So, I need a solution to convert ncdf to dfsu format as default format in MIKE 21 FM.

**Comment by ecomodeller** [comment]
MIKE 21 FM can read **dfs2** directly and will perform the interpolation to the unstructured grid.

If you still want a dfsu, take a look at this [example]https://github.com/DHI/mikeio/blob/master/notebooks/Dfsu%20-%20Distance%20to%20land.ipynb), where I calculate some values and save it to dfsu.

If you read the netcdf data with xarray, it can do the [interpolation](http://xarray.pydata.org/en/stable/interpolation.html#multi-dimensional-interpolation).

**Comment by robindang0573** [comment]
I got it. Thank you so much Sir.
