### ISSUE TITLE
Reading of dfs0 file not having time column such as Level-Area-Volume dfs0

### ISSUE THREAD

**Issue by amit1304in1** [DHI/mikeio#342]
I am trying to convert a dfs0 file which is not a time series in to a text file but while reading dfs0 mikeio is reading first column as datetime.
[BhamaAskheda_LevelAreaVolumeTable.zip](https://github.com/DHI/mikeio/files/8664155/BhamaAskheda_LevelAreaVolumeTable.zip)

**Comment by ecomodeller** [comment]
The purpose of MIKE IO is to make life easy for common workflows. You don't need MIKE IO to read this table.

You can use [mikecore](https://pypi.org/project/mikecore/) to read this file into a NumPy array or a dataframe
```
from mikecore.DfsFileFactory import DfsFileFactory
dfs = DfsFileFactory.DfsGenericOpen("BhamaAskheda_LevelAreaVolumeTable.dfs0")
data = dfs.ReadDfs0DataDouble()
data 
```
![image](https://user-images.githubusercontent.com/614215/167776911-3355f2f3-45e9-4a76-b7ea-bca147187eec.png)

**Comment by amit1304in1** [comment]
Dear Henrik,

Thanks for your quick response

Best regards

Amit Garg

**Comment by amit1304in1** [comment]
Thanks for you reply. It worked for me
