### ISSUE TITLE
Read dfs0 with many items

### ISSUE THREAD

**Issue by daniel-caichac-DHI** [DHI/mikeio#345]
**Describe the bug**
Hi, so I have 2 dfs0 files (outputs of the same model), one has like 15 columns, the other has +800 columns, 1 year of data (~130 mb).
I have 2 environments:
 * One with  `mikeio 0.11.1` and python `3.9.5` in that one I can read both files.
 * Another one with mikeio `1.0b0` (also tested `1.0b2`) and python `3.8.12` and that one can only read the smaller file.

**To Reproduce**

`from mikeio import Dfs0`
`file=r'large_file.dfs0'`
`ds=Dfs0(file).read()`
--> recursion error

**Expected behavior**
Open the file

**Screenshots**
![image](https://user-images.githubusercontent.com/97288080/168999544-e6b81737-3c00-4376-bd40-669d2f24e11f.png)

**System information:**
 - Python version = `3.8.12`
 - MIKE version = `1.0b0`

I will try updating to `python 3.9.5` to see if that fixes it

**Comment by daniel-caichac-DHI** [comment]
Thanks, I just tested with python `3.9.5` and mikeio `1.0b0` and it crashed, so it is a mikeio thing.

**Comment by ecomodeller** [comment]
Yes, it is a problem introduced in MIKE IO 1.0.
