### ISSUE TITLE
dealing with point and variable name in item name

### ISSUE THREAD

**Issue by Hendrik1987** [DHI/mikeio#348]
**use case**
In `.dfs0`, `.dfs2` and `.dfsu` point outputs of MIKE models, the item name can contain information of the variable but also the name of the point: `['Point 1: Hm0', 'Point 2: Hm0', 'Point 1: Tp', Point 2: Tp']`. 
To get all variables at one location, an intermediate step is required: E.g., `dfs = mikeio.read()`, find the items a la `items = [i.name for i in dfs.item if 'Point 1' in i]` and then `ds = dfs.read(_, items = items)`.

**wildcard option**
One solution could be to allow a wildcard or [re](https://docs.python.org/3/library/re.html#) in the `items` input argument, for example `ds = mikeio.read(items = ['Point 1:*])`. This is available on read, and can be used to load only parts of the file into memory.

**point name to dimension option**
A probably less robust, additional feature could be the option to split the item name and to recognize the point name as a dimension of the `geometry`. For example something like `ds = dfs.read(_, point_name_to_dimension = True)` (default False), which will loop through the item names, split on ': ' and rearrange the data accordingly. The `ds.geometry` would then have an extra dimension `point`, which would become available to the `.sel` methods and maintained in `.to_xarray().to_netcdf()`, to only mention two nice applications in my mind.

**context**
One could argue that this is too specific and outside the scope of mikeio. On the other hand, to store effectively an additional dimension as part of the variable name seems very specific to the `.dfs` file format and I have not come across it in for example `.nc` model outputs.

**Comment by Hendrik1987** [comment]
@daniel-caichac-DHI : I think you had a use case the other day, where something like this could be handy.

**Comment by daniel-caichac-DHI** [comment]
Yeah so what I wanted was to have in a netcdf (or xarray) the points with coordinates, items and name such that I could do something like 
ds.Points1 -> shows me the variables (surface elevation, u, v, etc) and the coordinates of point 1 (easting, northing), however I could not manage to do it in a smart way.

**Comment by ecomodeller** [comment]
I am not yet convinced that this is necessary, it suppose it is mostly relevant for dfs0, where you can read the entire file into memory and filter afterwards, like this for example.

![image](https://user-images.githubusercontent.com/614215/169477931-808bfc6a-73c7-4225-88a0-43de0d0c352b.png)

But I agree that it would be nice with wildcards.

**Comment by Hendrik1987** [comment]
Not necessary, but a very nice enhancement (of course that is subjective). Two situations where your suggestion fails (not all covered in my original comment to be fair):

1. Wave spectra as `.dfs2` or `.dfsu`
2. Saving multiple point outputs to a nicely formatted `.nc` file, as sometimes requested

Again, everything can already be achieved. For .dfs0 via `.groupby` and `.to_xarray` for example. 

If there are not enough mikeio user finding respective thin wrappers useful, then that is of course appreciated.

**Comment by Hendrik1987** [comment]
Closing it for now then. Maybe it can be picked up as nice to have at a later stage..

**Comment by Hendrik1987** [comment]
Closing it for now then. Maybe it can be picked up as nice to have at a later stage..

**Comment by Hendrik1987** [comment]
The original issue is actually resolved.

**Comment by jsmariegaard** [comment]
I like the idea of being able to read items matching a wildcard *

**Comment by ecomodeller** [comment]
> **use case** In `.dfs0`, `.dfs2` and `.dfsu` point outputs of MIKE models, the item name can contain information of the variable but also the name of the point: `['Point 1: Hm0', 'Point 2: Hm0', 'Point 1: Tp', Point 2: Tp']`. To get all variables at one location, an intermediate step is required: E.g., `dfs = mikeio.read()`, find the items a la `items = [i.name for i in dfs.item if 'Point 1' in i]` and then `ds = dfs.read(_, items = items)`.
> 
> **wildcard option** One solution could be to allow a wildcard or [re](https://docs.python.org/3/library/re.html#) in the `items` input argument, for example `ds = mikeio.read(items = ['Point 1:*])`. This is available on read, and can be used to load only parts of the file into memory.
> 
> **point name to dimension option** A probably less robust, additional feature could be the option to split the item name and to recognize the point name as a dimension of the `geometry`. For example something like `ds = dfs.read(_, point_name_to_dimension = True)` (default False), which will loop through the item names, split on ': ' and rearrange the data accordingly. The `ds.geometry` would then have an extra dimension `point`, which would become available to the `.sel` methods and maintained in `.to_xarray().to_netcdf()`, to only mention two nice applications in my mind.
> 
> **context** One could argue that this is too specific and outside the scope of mikeio. On the other hand, to store effectively an additional dimension as part of the variable name seems very specific to the `.dfs` file format and I have not come across it in for example `.nc` model outputs.

There is now an option to use a wildcard in the items selector being. See #383

**Comment by Hendrik1987** [comment]
Thanks for accommodating this even after I closed the request - so this stays closed! :-)
