### ISSUE TITLE
xarray as a dependency?

### ISSUE THREAD

**Issue by maximlt** [DHI/mikeio#36]
Hi!

I've been following this repo for quite some time already and am happily surprised to see how fast it's growing, it looks very promising and helpful!

I've seen that you've implemented a ``Dataset`` class to store multidimensional arrays. I just wanted to check if you're aware of [xarray](http://xarray.pydata.org/en/stable/) which is a powerful and complete library that provides such an object. I'm also mentioning ``xarray`` here as I had a tiny project (not open-sourced yet) that allowed to read .dfs2 files as xarray dataset objects, that worked quite well and allowed to easily do such a thing:
```python
import tinydfs2package
xarray_result = tinydfs2package.read("output.dfs2")
max_values = xarray_result.max(dim="time")  # xarray allows to express your intent very clearly
```

As a bonus question, do you consider the API stable already? If not, do you have any ETA?

Thanks!

**Comment by ecomodeller** [comment]
I'm very aware of xarray, superb library (as you can see in [this notebook](https://github.com/DHI/mikeio/blob/master/notebooks/Dfs2%20-%20Global%20Forecasting%20System.ipynb).) Xarray is fantastic for structured grids, which we also use, but has no support as far as I know for unstructured grids. 

So what to do, perhaps adding a `to_xarray` method to the dfs1, dfs2, dfs3 classes?

I think `mikeio` makes working with dfs files in Python a lot easier (no kidding...) and I use it for productive things all day long, but I think we are still improving on the API, and sorry there is no ETA.

It is great to hear that many people find it a useful library, that will certainly help making it better.

**Comment by maximlt** [comment]
Good to hear you already know it (that was obvious in hindsight!). Adding a ``to_xarray`` method for these 3 file types sounds like a good idea. I wouldn't be surprised to see that potential users of that library won't be developers but civil engineers basically. Since ``xarray`` is now the standard for multidimensional arrays in the pydata ecosystem, it'd be nice to expose them to this library here as they may not know about it.

Just some random thoughts, I liked using xarray dataset objects in my little tool as I stored the .dfs2 file metadata in the dataset ``attrs``. I used some of that info to precise the ``__repr__``, idea I took from *dhitools* [here](https://github.com/robjameswall/dhitools/blob/b5ba0613f7f50aa0d66e0a0951ede757427af1cf/dhitools/dfs.py#L75). I also used that metadata stored in the dataset as a support to write the result of some computation (such as the example above) to another .dfs2 file.

**Comment by jsmariegaard** [comment]
I like both ideas: adding to_xarray() for dfs123 but also letting all classes have an `attrs` attributes that is filled when you read from file and can be re-used when you create a new file. And a dfs.summary() method would also be super nice - should essentially print the metadata from `attrs` to screen. 
Thanks

**Comment by rhaDHI** [comment]
If you add xarray as a dependency, please add it as an optional dependency to keep mikeio lightweight. This is what pandas does with external file formats like parquet. They raise import errors if missing in to_parquet, see https://github.com/pandas-dev/pandas/blob/8eb1048a2802e7ebd50240873eb55b39a03f220b/pandas/compat/_optional.py#L47

**Comment by ecomodeller** [comment]
I think that is a good compromise. I did a similar thing here https://github.com/DHI/mikeio/blob/b0cb11880ab1b0a23f69efbaeb5f39902382d2cd/mikeio/mesh.py#L96 where I import shapely, which will raise an error if it is not installed. Nice to have, but not essential.

**Comment by rhaDHI** [comment]
Do you then keep a separate install/dev requirements list for running test pipelines?

**Comment by ecomodeller** [comment]
I have not solved that yet, but suppose that's the way to do it.

**Comment by maximlt** [comment]
Good idea to have xarray and other heavy modules as optional dependencies! :)

You could add an `optional` key in the dict passed to `extras_require` that lists theses optional dependencies:
``extras_required = {"optional": ["shapely", "xarray"]}``
And install them in your CI or locally with ``pip install .[optional]``

**Comment by rhaDHI** [comment]
@ecomodeller I see that you added xarray to optional dependencies. If the to_xarray method works I guess we can merge thath branch and close this?

**Comment by ecomodeller** [comment]
It has to be be made general, so it works for all types of datasets, 0d, 1d, 2d, 3d, unstructured, rotated...

**Comment by ecomodeller** [comment]
1. The latest updates to MIKE IO is heavily inspired by xarray, but we chose not to rely completely on xarray, to have more control, and make sure a processed dataset can be stored as a valid dfs file.
2. There is now a [DataArray.to_xarray()](https://github.com/DHI/mikeio/blob/97b122579fd2cdde6a70b80adedfa8702d14db3f/mikeio/dataarray.py#L547) method.
3. The stable version of MIKE IO 1.0 is scheduled for release in May 2022.
