### ISSUE TITLE
Add method to dfsu class to read mesh from dfsu object and return a mesh object

### ISSUE THREAD

**Issue by derekeden** [DHI/mikeio#37]
Hello there,

First off, great work on this python pkg. Very useful.

I had starting developing something similar with a lot of the same functionality a while back that worked with some data structures/proprietary code at work, and have looked at this a number of times for help. I will upload my package to github in the near future once it's ready (minus the proprietary parts), hopefully you/others find it helpful.

**Question....**

The mesh class uses the DHI.Generic.MikeZero.DFS.mesh.MeshFile.ReadMesh function to open the mesh file, and extract the mesh information.

When a dfsu file is read, you can extract the same type of mesh information out of it using the DHI.Generic.MikeZero.DFS.DfsFile.ReadStaticItem function. This is fine, but I'm wondering if there is a way (or if you could implement a method) that takes in the dfsu file object (DHI.Generic.MikeZero.DFS.DfsFile) and pass it into some SDK function that will return a mesh object (or similar), so it has all the same properties as a DHI.Generic.MikeZero.DFS.mesh.MeshFile.

Or some other way of using the SDK to extract the mesh out of the dfsu file object without using static items?

The reason I say this is because the mesh of the dfsu could re-use the existing mesh class code to store it's mesh.

Thank you!

**Comment by jsmariegaard** [comment]
Thanks. Looking forward to seeing your work - please let us know once uploaded. 

Would you like to save the mesh from your dfsu as a file or what are you trying to achieve?

**Comment by derekeden** [comment]
Will do! Sorry if I was unclear...

Right now I am reading the mesh from the dfsu file object (DHI.Generic.MikeZero.DFS.DfsFile) by using the DHI.Generic.MikeZero.DFS.DfsFile.ReadStaticItem function.

Is there any way to pass this dfsu file object into an SDK function that will return an object that has the same properties as a mesh file object that is opened via the DHI.Generic.MikeZero.DFS.mesh.MeshFile.ReadMesh (returns a DHI.Generic.MikeZero.DFS.mesh.MeshFile object).

The reason I ask is because there is a mesh class that is currently storing mesh information from a mesh file, but if the above is possible, the exact same class could be used to store the mesh of a dfsu class object.

Thanks!

**Comment by jsmariegaard** [comment]
I am not sure - but I think it could be made without too much effort. I am planning to go through the mesh + dfsu functionality after Easter. 

I think also [dhitools](https://github.com/robjameswall/dhitools) by [robjameswall](https://github.com/robjameswall) can do that with their dfsu class.

**Comment by derekeden** [comment]
thanks so much!!!!!

actually found exactly what I needed from that code.

I was opening the dfsu file using DfsFileFactory.DfsGenericOpen which opens the dfsu but contains the mesh information in the StaticItems...when opening the dfsu using DfsFileFactory.DfsuFileOpen it returns an object where the mesh is accessible using the same code as when opening a mesh file using  DHI.Generic.MikeZero.DFS.mesh.MeshFile.ReadMesh...very much appreciated!
