### ISSUE TITLE
Dfsu: single element spatial selection yields ValueError

### ISSUE THREAD

**Issue by ovho-dhi** [DHI/mikeio#376]
**Description**
Performing a spatial selection with a Polygon that covers only a single element, the dfs.read() method throws a ValueError "Number of named dimensions does not equal data ndim",while ds.sel() method results in a GeometryPoint2D Dataset.

**To Reproduce**
In [13) >> https://github.com/DHI/mikeio/blob/dfsu_area_selection/notebooks/spatial_Selection_Element_IDs.ipynb

**Expected behavior**
consistent output of a GeometryPoint2D Dataset.

**System information:**
 Python 3.9.12
 MIKE IO 1.0.1

**Comment by jsmariegaard** [comment]
Thanks @ovho-dhi , I can confirm that this is a bug.
