### ISSUE TITLE
Fast writing of dfs0

### ISSUE THREAD

**Issue by jsmariegaard** [DHI/mikeio#38]
I am currently creating some relatively big dfs0 files with more than 1e6 time steps. This takes a long time with the current implementation of Dfs0.create(). In the DHI matlab toolbox you would use the .NET function MatlabDfsUtil.DfsUtil.WriteDfs0DataDouble(). Could we not do the same in mikeio?

**Comment by jsmariegaard** [comment]
It seems that it's actually supported directly from Dfs0Util. Yeah. 

from DHI.Generic.MikeZero.DFS.dfs0 import Dfs0Util
Dfs0Util.WriteDfs0DataDouble(dfsfile, times, data)

http://doc.mikepoweredbydhi.help/webhelp/2019/DHI_DFS/html/M_DHI_Generic_MikeZero_DFS_dfs0_Dfs0Util_WriteDfs0DataDouble.htm

Will test later

**Comment by jsmariegaard** [comment]
Hmm I cannot make it work - the thing missing is casting numpy ndarray to 2d .NET Array of floats which is required by WriteDfs0DataDouble(). I have tried a number of things and searched on the web. I did find something that we maybe could use - see robbmcleod's post in this thread https://github.com/pythonnet/pythonnet/issues/514 - "Hi, I wrote a Python-side Numpy <-> .NET conversion functions that use ctypes.memmove" - could it make sense to add as dotNetHelper.py or something?

**Comment by jsmariegaard** [comment]
The function, asNetArray, from the above post seems to solve the problem. I think this should go in a new file (and class) dotNet_utils.py. Agree?

**Comment by ecomodeller** [comment]
How about just `dotnet.py`? I don't think we need a class.

**Comment by JesperGr** [comment]
I guess a Dfs0Util.WriteDfs0DataDoubleArray function returning things in a row major order format would solve that problem, right?

**Comment by jsmariegaard** [comment]
Thanks, but we got it sorted in another branch https://github.com/DHI/mikeio/blob/to_from_dotnet/mikeio/dotnet.py :-) will merge when we get some time again

**Comment by jsmariegaard** [comment]
closed by #43
