### ISSUE TITLE
Single vs double precision

### ISSUE THREAD

**Issue by ecomodeller** [DHI/mikeio#40]
Is it correct to convert all data to double precision
https://github.com/DHI/mikeio/blob/b6a3272e507d0c7594c9f6077dc3f9d3061458f3/mikeio/dfsu.py#L73

Or should it be `dtype=np.float32` (i.e. single precision)?

**Comment by jsmariegaard** [comment]
All calculation in MIKE FM is done with double precision and all outputs are written to disk with single precision. I think it's sensible to do the same in mikeio: Read from disk and convert to double precision for further work.

**Comment by ecomodeller** [comment]
I agree that it is a sensible default. But how about this approach where it can be set if you don't really need double precision and rather wants to have a smaller memory footprint?

```

>>> import numpy as np
>>> from mikeio.dfsu import Dfsu
>>> filename = "flow.dfsu"
>>> dfs = Dfsu()
>>> dp = dfs.read(filename,item_numbers=[1])
>>> dp.data[0].dtype
dtype('float64')
>>> dp.data[0][1,0]
-0.09249680489301682
>>> sys.getsizeof(dp.data[0])
1776112
>>> dfs = Dfsu(datatype=np.float32)
>>> sp = dfs.read(filename,item_numbers=[1])
>>> sp.data[0].dtype
dtype('float32')
>>> sp.data[0][1,0]
-0.092496805
>>> sys.getsizeof(sp.data[0])
888112
```

**Comment by jsmariegaard** [comment]
super cool
