### ISSUE TITLE
Read dfs0 with repeated columns names

### ISSUE THREAD

**Issue by daniel-caichac-DHI** [DHI/mikeio#401]
**Describe the bug**
So, Mike by default adds a lot of text to Dfs0 outputs, for instance if I have a point called 'Some_Random_Point' and I choose to get Total/Sea/Swell parameters, I should 3 columns named like:

* `Some_Random_Point: Significant Wave Height [m]`
* `Some_Random_Point: Significant Wave Height: W [m]`  (sea parameters)
* `Some_Random_Point: Significant Wave Height: S [m]`  (swell parameters)

However, if the name is too long it might be truncated and the Dfs0 columns outputs (column names) might end up being something like:
* `Some_Random_Point: Significant Wave Heig [m]`
* `Some_Random_Point: Significant Wave Heig [m]`  (sea parameters)
* `Some_Random_Point: Significant Wave Heig [m]`  (swell parameters)

So, all 3 names are the same. Unfortunately, MikeIO cannot read Dfs0 in the present version with repeated column names.
![image](https://user-images.githubusercontent.com/97288080/184348287-69592a23-fde6-4b09-a13b-5e703aeb25dd.png)

In a previous version , say `MikeIO 0.12.2` this was not an issue.

**To Reproduce**
`file=file_with_repeated_column_names.dfs0`
`Dfs0(file).read()`

**Comment by ecomodeller** [comment]
The goal of MIKE IO is to make it easier to do 98% of the tasks related to I/O of MIKE models (excluding MIKE 1D😟). Having repeated column names is a recipe for disaster.

If you have data like this, you have the option to go one level deeper and use mikecore-python directly to read this kind of data.
