### ISSUE TITLE
pfs to read and modify plc files

### ISSUE THREAD

**Issue by frma96** [DHI/mikeio#434]
Dear all,

I am using the mikeio.read_pfs to read, modify and rewrite pfs files. While this works well with .dfsu files, it gives troubles with .plc files.

Simply reading a plc file and rewriting the same identical renamed file makes it lose the colour palette (warning: "RGB_Color_Value defined multiple times").
Under the section [IMAGE_FILES], the ImageFileName goes from |\\dkcph1-stor2.dhi.dk\project... to '|\\dkcph1-stor2.dhi.dk\project..', with these '' symbols resulting in altering the path. 
In addition, changing the [DataFile] path section deletes sections and makes the file invalid. 

Please find attached the comparison between the two .plc files (the read plc and the rewritten and renamed file). 
The line of codes is the following:

main_dir_frv = '//dkcph1-ncr3626/FRMA/Iteration_flushing_py/postprocess_YEAR/'
file_frv = 'AD2D_d37_channel_0_duration_d'
file_path_plc = os.path.join(main_dir_frv, file_frv + '.' + filename_suffix_plc)
pfs_plc = mikeio.read_pfs(file_path_plc)

new_file_path_plc_input = os.path.join('|.\Try.dfu|')
pfs_plc.MIKE_ZERO_PLOT_COMPOSER.ACTIVE_X_PLOT.PLOT_PROPERTIES.Files.DataFile = new_file_path_plc_input
new_file_path_plc = os.path.join(main_dir_frv + 'try.plc')
pfs_plc.write(new_file_path_plc)

![image](https://user-images.githubusercontent.com/114576352/192996359-f5107be7-6669-4ec8-a154-671eb9a7ac5d.png)

![Capture](https://user-images.githubusercontent.com/114576352/192996819-a122a7d0-ae63-4fa3-98ea-95af359bdff1.PNG)
![Capture2](https://user-images.githubusercontent.com/114576352/192996824-c0c9283e-9463-4267-abe2-7fa44e07e14d.PNG)

**Comment by ecomodeller** [comment]
Ouch, those repeated 'RBG_Color_Value' are not easy to handle. 

In this case they should be interpreted as a list of values, and in other cases repeated keywords is an error. https://github.com/DHI/mikeio/pull/419#issuecomment-1248222634

@jsmariegaard had a solution to handle repeated keywords, I guess we have to bring this back in and think if there should be an option to treat repeated keywords as a list.

**Comment by jsmariegaard** [comment]
@frma96 thanks a lot for testing this. Much appreciated! The repeated Keywords is giving me a bit of a headache but we obviously need to solve it :)

**Comment by frma96** [comment]
Thank you :)
what kind of method could work in the meantime to get read of those repetitions error? This does not work :(
![image](https://user-images.githubusercontent.com/114576352/193293795-88164384-9f93-4b67-a856-39a4a9041245.png)

**Comment by jsmariegaard** [comment]
@frma96 - could you please test the branch version in #436? Does this solve your problem? Let me know if you need instructions on how to install the version in the branch.

**Comment by jsmariegaard** [comment]
@frma96 you were missing "DataFileName" in this line:

    pfs_plc.MIKE_ZERO_PLOT_COMPOSER.ACTIVE_X_PLOT.PLOT_PROPERTIES.Files.DataFile.DataFileName = new_file_path_plc_input

And regarding the False/false - I don't think it has any practical meaning.

**Comment by frma96** [comment]
@jsmariegaard thank you :) could you please instruct me on how to install the version in the branch?
(the DataFileName works now)

**Comment by jsmariegaard** [comment]
You can install from a branch [pfs-repeated-keywords](https://github.com/DHI/mikeio/tree/pfs-repeated-keywords) into an existing installation with:

    pip install --upgrade https://github.com/DHI/mikeio/archive/refs/heads/pfs-repeated-keywords.zip

**Comment by frma96** [comment]
@jsmariegaard it works now this way :) 
pfs_plc = read_pfs(file_path_plc, unique_keywords=False)
All the colour palette is kept intact, thank you so much!

**Comment by jsmariegaard** [comment]
@frma96  - thanks for reporting and testing. This is important for the success of MIKE IO and thereby for all of us using it :-)
