### ISSUE TITLE
Reading and writing pfs with a keyword that has multiple empty string is failed. 

### ISSUE THREAD

**Issue by mohm-dhi** [DHI/mikeio#470]
there is a bug that I am working on it or if you already have a solution for it please fix it. 
if a keyword has couple of empty strings like this
![image](https://user-images.githubusercontent.com/65772896/202230182-d5b64ad8-7a51-4b60-81ae-76d5696f6ffa.png)

if you want to write it back to a pfs file it shows like this on the new file. 

![image](https://user-images.githubusercontent.com/65772896/202230416-69dafc87-957c-41ba-b14b-6b6553b95af8.png)

**Comment by jsmariegaard** [comment]
This will be fixed with #464 - I've added a test for it https://github.com/DHI/mikeio/pull/464/commits/5a724ef475eb243bd7902e7edd0b3cf1eebbb49c
