### ISSUE TITLE
dfsu.read() parameter does not read all parameters

### ISSUE THREAD

**Issue by JohannaZ** [DHI/mikeio#51]
Dear mikeIO Team,
I have a script reading a Mike3DSigma file, which does not run anymore, bellow the bug description:

**Describe the bug**
I´m reading a dfsu file with:
data, time, names = dfs.read(dfsu_f)
If I print names I used to get the output ['Current Speed', 'Temperature']

Now I get the output [Z coordinate <ItemGeometry3D> (meter), Current speed <Current Speed> (meter per sec)]
First result I got with mikeio version 0.3.0, second (broken) one I get since version 0.4.1
I went up with the version to check since which version the read function started to read the parameters different.

I also had a look in the dfsu.read function, but as far as I understand the code, dfsu.read should still scip the first parameter (Dynamic Z) if the file is a 3dSigma / SigmaZ file. So I couldn´t really find out what's wrong here.

**To Reproduce**
pip install mikeio==0.3.0
data, time, names = dfs.read(dfsu_f) #dfsu_f -> 3Dsigma model with parameter current speed and temp
print (names)
-------------------------------------------
pip install mikeio==0.4.1
data, time, names = dfs.read(dfsu_f) #dfsu_f -> same model as before
print (names)

**Expected behavior**
dfsu.read() reads all parameters which are in the model

**Screenshots**

**System information:**
 - Python version = 3.6
 - MIKE version 0.3.0 (dfsu_read() intact, 0.4.1 dfsu_read() broken

**Comment by ecomodeller** [comment]
I will take a look at it. But on second thought, I think it is better to should include Dynamic Z, but remember that it node values and not element values, and thus different size.

**Comment by JohannaZ** [comment]
Sounds good to me, as long as all parameters are included, because at the moment it seems like only the first two occurences (Dynamic Z and Speed) are read and the third (Temp) is somehow scipped or ignored. 
Thanks for your fast response!
