### ISSUE TITLE
dfsu file of manning M cannot be opened

### ISSUE THREAD

**Issue by Hendrik1987** [DHI/mikeio#516]
**Describe the bug**
I have a dfsu file of a friction map, which I would like to open in `mikeio`. I get the following error messages:
![image](https://user-images.githubusercontent.com/29595985/209214024-a065462e-0df7-41ab-8e7c-1a44a9ab8e66.png)

The file is accepted by a MIKE 21 HD run and in the data utility it looks like this:
![image](https://user-images.githubusercontent.com/29595985/209214298-18c64a6e-8ab1-475b-b80f-cdc6235b59bd.png)

**What I tried**
I did create, save and reload a `mikeio.dataset` with `EUMType.Mannings_M`, `EUMUnit.meter_pow__1_per_3__per_sec` without any problems. I did then also open this 2nd dfsu file in the data utility and could not find a difference.

**System information:**
 - Python 3.11.0
 - MIKE IO version 1.2.4

**Comment by jsmariegaard** [comment]
Could you send the file to me? Then I can try.

**Comment by jsmariegaard** [comment]
This seems to be due to an empty item name. Will try to confirm with another file. If this is indeed the problem it can be transferred to https://github.com/DHI/mikecore-python

**Comment by Hendrik1987** [comment]
I have created a .dfsu file in Mesh Generator with empty item. I have also imported the problematic dfsu file in Mesh Generator and exported again as .dfsu with an item name. Will send you both files. 

I can read both files in mikeio. I am still puzzled what the problem or combination of problems in the original file is... But my problem at hand is solved now.

**Comment by jsmariegaard** [comment]
Thanks. Strange. Could you please send me the files? Then I can see if I can find a difference between those and the one you send me last time.

**Comment by jsmariegaard** [comment]
I wonder if it could be due to the missing type/units of the static items? 

![image](https://user-images.githubusercontent.com/34088801/210370667-743b43f1-3ac3-4b46-8bb3-c0fb69193d0f.png)

**Comment by jsmariegaard** [comment]
It is actually surprising that the file "works" when you consider the names of the static items: It contains two items named "Z-coordinates" (4 and 5) and two items named "Nodes per element" (8 and 9). Item 5 should have been "code" and item 9 should have been "connectivity". But when the dfsu file is read by MIKE core, the name, type and unit are _not_ checked, it just read the static items assuming that they are: 1:node id, 2:x, 3:y, 4:z, 5:code, 6:element id, 7:element type, 8:num of nodes, 9:connectivity.

**Comment by Hendrik1987** [comment]
Good observation! This appears to have been fixed by the import and export through Mesh generator.
Although MIKE seems to be more forgiving (.dfsu can be opened in MIKE Zero and used for MIKE 21 HD run), I would consider the file as incomplete / incorrect.
