### ISSUE TITLE
dfsu.read does not read wave files

### ISSUE THREAD

**Issue by ustoeber** [DHI/mikeio#53]
**Describe the bug**
I'm trying to read a MIKE SW output file, but I get the error message "ValueError: 5100 is not a valid EUMUnit"

**To Reproduce**
`from mikeio import Dfsu`
`dfsu = Dfsu()`
`file_test = r'C:\Program Files (x86)\DHI\2020\MIKE Zero\Examples\MIKE_21\FlowModel_FM\ST\Torsminde\Data\Waves\Wave_Sim.dfsu'`
`res = dfsu.read(file_test)`

**Expected behavior**
dfsu.read returns data in the file

**System information:**
 - Python version: 3.6.10
 - MIKE version: 2020
 - mikeio version: 0.4.2

**Comment by ecomodeller** [comment]
Radiation stress was missing from the list of units. This commit should fix it. 
https://github.com/DHI/mikeio/commit/b8a5af8139e439b73189e7a22aba4630321b563d
Install a new version from the master branch and see if it works better.

**Comment by ustoeber** [comment]
Now it works. Thanks a lot for the fast solution!
