### ISSUE TITLE
github action to test downstream functionality

### ISSUE THREAD

**Issue by jsmariegaard** [DHI/mikeio#530]
Recently, I change in MIKE IO made all tests fail in the downstream library FMskill. Should we have a github action that tests downstream libraries? For know mostly FMskill but in the future potentially more applications?

**Comment by ecomodeller** [comment]
Testing downstream dependencies is very uncommon. But it is used by the R community, as seen in this quote from [CRAN - The **C**omprehensive **R** **A**rchive **N**etwork](https://cran.r-project.org/), name inspired by CPAN (Comprehensive Perl Archive Network), package repos similar to PyPI.

> For a package update, please check that any packages depending on this one still pass R CMD check: it is especially expected that you will have checked your own packages. Reverse dependencies can conveniently be checked using tools::check_packages_in_dir(reverse = list()), and changes in check status subsequently be analyzed using tools::check_packages_in_dir_changes(). A listing of the reverse dependencies of the current version can be found on the CRAN web page for the package, or be obtained via tools::package_dependencies(reverse = TRUE). If possible, check reverse strong dependencies, reverse suggests and the recursive strong dependencies of these (by tools::package_dependencies(reverse = TRUE, which = "most", recursive = "strong")).

Nevertheless, I have given it a shot in #531 where I install both mikeio and fmskill from their respective main branches.

I am not sure it scales when the number of dependencies gets larger.
