### ISSUE TITLE
Optimize _findTopLayerElements for sigma only

### ISSUE THREAD

**Issue by ecomodeller** [DHI/mikeio#542]
The current implementation works for sigma and sigma-z
https://github.com/DHI/mikeio/blob/5f29d52e10680adde6ef20cb6a1c0ca9e550292f/mikeio/spatial/FM_geometry.py#L1628

 but it must be possible to construct this list much faster for a pure sigma file, than looping over all elements.

**Comment by jsmariegaard** [comment]
I guess so - if you know the 2d geometry and the number of layers - it should just be a matter of stride
