### ISSUE TITLE
Allow specification of dtype for Dfs3.read() (as implemented in Dfs2.read() )

### ISSUE THREAD

**Issue by Snowthe** [DHI/mikeio#558]
The Dfs2.read() method allows you to specify the dtype - and defaults to np.float32
The Dfs3.read() method is lacking this option - which then means that it ends up using float64.

Sometimes, especially with large files that can create memory issues, it would be useful to be able to specify the dtype also for Dfs3 files (and e.g. use np.float32 to). Also, this would streamline the two methods.

**Comment by ecomodeller** [comment]
@Snowthe would you like to create a PR, it seems like a manageable task?

**Comment by Snowthe** [comment]
Done. Hope I did it the right way; fairly new to working with git.
