### ISSUE TITLE
raise ValueError(f"Item names must be unique ({item_names})!")

### ISSUE THREAD

**Issue by JustinPringle** [DHI/mikeio#564]
I'm getting a funny error when trying to read a dfs0 result file I created using Mike Hydro
I generated the result file with Mike Hydro so I am unsure why there are duplicate names as I can't see any in my setup files (i.e. all my branches and xns are unique).

**Comment by ecomodeller** [comment]
Try to read few items: 
```python
ds = mikeio.read("file.dfs0", items=[0,1])
```

Could it be that the names are not unique, because of finite length of the item names?
