### ISSUE TITLE
Support for Python 3.8

### ISSUE THREAD

**Issue by col16** [DHI/mikeio#58]
The [README](https://github.com/DHI/mikeio/blob/master/README.md) for this project states that pythonnet doesn't support Python 3.8. However the latest version of pythonnet (2.5) does support Python 3.8. Can mikeio be updated to depend on pythonnet 2.5 please?

**Comment by jsmariegaard** [comment]
Hi, we are aware of this and will be working on it after the summer break (August). Cheers

**Comment by ecomodeller** [comment]
#60 Should fix this
