### ISSUE TITLE
DFSU  read(x,y) is 20-30 times slower on Linux when compared with Windows

### ISSUE THREAD

**Issue by bhlevca** [DHI/mikeio#598]
**Describe the bug**
DFSU  read(x,y) is 20-30 times slower on Linux when compared with Windows from a large DFSU

**To Reproduce**
load a large dfsu file like in [Dfsu - 3D sigma-z.ipynb](https://github.com/DHI/mikeio/blob/main/notebooks/Dfsu%20-%203D%20sigma-z.ipynb) 

**Expected behavior**
I would expect similar timing not such a huge performance hit on Linux. I am curious if you can reproduce the Linux slowness.  Everything else works fast on my Linux machine.

**System information:**
 - Python version: 3.11.4
 - MIKE IO version: 1. 6.2
Both OS es have the same version for Python and mikeio

**Comment by bhlevca** [comment]
It appears that it has something to do with the CPU. I have an AMD Ryzen.  NumPy is slower when using the blas lib. On Intel platforms numpy is using MKL

**Comment by ecomodeller** [comment]
@bhlevca can we agree that this is not directly related to MIKE IO?
