### ISSUE TITLE
Delete value not set in dfs0 write?

### ISSUE THREAD

**Issue by rhaDHI** [DHI/mikeio#61]
https://github.com/DHI/mikeio/blob/637dc5fb9b816052b4c9c3d017a9e3188ad2ecef/mikeio/dfs0.py#L140-L143

**Comment by ecomodeller** [comment]
Please elaborate, I don't get what is wrong here

**Comment by rhaDHI** [comment]
d is never used

**Comment by ecomodeller** [comment]
`d` is a reference to a part of the `data` array, which gets modified and is written to the file. I have added a test to prove that it works as expected 86711d0e739a23e8a32d9bcd6e5887c737e5f043

Do you agree, or have I missed something?

**Comment by rhaDHI** [comment]
We can fix this issue in a similar way: https://github.com/DHI/mikeio/issues/30

**Comment by ecomodeller** [comment]
![image](https://user-images.githubusercontent.com/614215/90403528-665dc800-e0a1-11ea-883e-5a3fec68b708.png)
