### ISSUE TITLE
mikeio fails when reading preprocessed layer information

### ISSUE THREAD

**Issue by TroelsNV** [DHI/mikeio#618]
**Describe the bug**
MIKEIO returns an exception when reading preprocessed dfs2 filer containing layer information. The bug occures in the function _valid_timesteps because the time_step_file is set to 0 (line 138 in mikeio.dfs._dfs.py). when creating the time variable in line 142 pandas.date_range fails because the length is set to 0.

**To Reproduce**
import mikeio

# read geolenses:
mikeio.read('NVFyn_MST_SceTillad_GeoLenses.dfs2')

**Expected behavior**
Expected return of mikeio.Dataset

**Screenshots**
![image](https://github.com/DHI/mikeio/assets/16219980/1211748d-144b-4554-a6b6-f1f86d87ec79)

**System information:**
 - Python version 3.12.0
 - MIKE IO version 1.6.3

**dataset:
NB! remove .txt extension
[NVFyn_MST_SceTillad_GeoLenses.dfs2.txt](https://github.com/DHI/mikeio/files/13278165/NVFyn_MST_SceTillad_GeoLenses.dfs2.txt)

**Comment by ecomodeller** [comment]
Hi @TroelsNV the error occurs because the TimeStep defined in the file is 0.0 seconds.
![image](https://github.com/DHI/mikeio/assets/614215/42f6e1d4-ec63-482c-81a5-f87425404e84)

Since the file only contains a single timestep it is somewhat useless information what the spacing in time is.

**Comment by ecomodeller** [comment]
I haven't encountered this problem before, but I agree that it should be readable by MIKE IO.

What tool created the file?

**Comment by TroelsNV** [comment]
The files were created by MIKESHE during preprocessing.

**Comment by ecomodeller** [comment]
It is not possible to create such a file with MIKE Zero.
![image](https://github.com/DHI/mikeio/assets/614215/d1320cf0-bbef-4dd9-b182-b29fc5cb5064)

**Comment by ecomodeller** [comment]
@watermain any comments from someone familiar with MIKE She?

**Comment by TroelsNV** [comment]
@ecomodeller I just checked with my colleague (I didn't create the files). The files were created by MIKE She as a part of the preprocessing.

**Comment by ecomodeller** [comment]
> I can confirm that MIKE She creates this file (and at least a few others) with a 0 length time step. The whole time axis does not have a meaning here, this is a strictly static grid. We could make changes to the MIKE She code, not a big deal, but
> 
> * this would only be released some time mid or end next year
> * If the dfs API allows this I would consider it a valid setting, even if the GUI doesn´t. If it is not considered to be valid then the dfs API should throw an error.
> 
> The mikeio code shown above is just trying to get a start and end date, right? Would it be an option to use the start date only if there is just a single time anyway?

I agree, for static data it would be preferable not having to specify anything related to time, but that is not how the dfs format is designed. I am suggesting to handle it in #620.
