### ISSUE TITLE
small inconcistency in time dimension for time-invariant data arrays?

### ISSUE THREAD

**Issue by Hendrik1987** [DHI/mikeio#643]
Selecting one time step and averaging over time both result in time-invariant dataarrays - so far so good.
But the former seems to have dimension time = 1 and the latter has no time dimension.
Here the example for Grid2D, which broke my to .tiff conversion for the 2nd case.

![image](https://github.com/DHI/mikeio/assets/29595985/0394b5a0-819f-457e-b304-829a9b54446f)

Is there a reasoning behind this behaviour, which I am overlooking? Thanks!

**System information:**
 - Python 3.10.0
 - mikeio 1.6.3

**Comment by ecomodeller** [comment]
@Hendrik1987 how did you select in time?
I get no time dimension.

```
>>> ds = mikeio.read("waves.dfs2")
>>> ds
<mikeio.Dataset>
dims: (time:3, y:31, x:31)
time: 2004-01-01 00:00:00 - 2004-01-03 00:00:00 (3 records)
geometry: Grid2D (ny=31, nx=31)
items:
  0:  Sign. Wave Height <Significant wave height> (meter)
  1:  Peak Wave Period <Wave period> (second)
  2:  Mean Wave Direction <Mean Wave Direction> (degree)
>>> ds.isel(time=0)
<mikeio.Dataset>
dims: (y:31, x:31)
time: 2004-01-01 00:00:00 (time-invariant)
geometry: Grid2D (ny=31, nx=31)
items:
  0:  Sign. Wave Height <Significant wave height> (meter)
  1:  Peak Wave Period <Wave period> (second)
  2:  Mean Wave Direction <Mean Wave Direction> (degree)
>>> ds = mikeio.read("waves.dfs2",time=0)
>>> ds
<mikeio.Dataset>
dims: (y:31, x:31)
time: 2004-01-01 00:00:00 (time-invariant)
geometry: Grid2D (ny=31, nx=31)
items:
  0:  Sign. Wave Height <Significant wave height> (meter)
  1:  Peak Wave Period <Wave period> (second)
  2:  _Mean_ Wave Direction <Mean Wave Direction> (degree)
ds.sel(time="2004-01-01")
<mikeio.Dataset>
dims: (y:31, x:31)
time: 2004-01-01 00:00:00 (time-invariant)
geometry: Grid2D (ny=31, nx=31)
items:
  0:  Sign. Wave Height <Significant wave height> (meter)
  1:  Peak Wave Period <Wave period> (second)
  2:  Mean Wave Direction <Mean Wave Direction> (degree)
>>>
```

**Comment by Hendrik1987** [comment]
Sorry for the incomplete / incorrect report.
It actually does not happen during time select or aggregation, but when reading an time-invariant dfsu:
![image](https://github.com/DHI/mikeio/assets/29595985/5082e9db-0399-4bef-a62e-86ba1cc848e9)

**Comment by ecomodeller** [comment]
> Sorry for the incomplete / incorrect report @ecomodeller It actually does not happen during time select or aggregation, but when reading a time-invariant dfsu: ![image](https://private-user-images.githubusercontent.com/29595985/304675514-5082e9db-0399-4bef-a62e-86ba1cc848e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MDE5MDcsIm5iZiI6MTcwNzkwMTYwNywicGF0aCI6Ii8yOTU5NTk4NS8zMDQ2NzU1MTQtNTA4MmU5ZGItMDM5OS00YmVmLWE2MmUtODZiYTFjYzg0OGU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE0VDA5MDY0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU0OWQ3YTY1NmQxYzRmOTU0OTRhNDliMmYwYjAxZmM3NjkyMTY2M2IwZjMzZDc0MmJkZDI2MTVmMWVjNWIxOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uKzjNSCHw7CuohvnV7zZSJOXuflqtqra8nne4VMUOXM)

That is by design. If you know you are expect a time-invariant dfs file, you can do `mikeio.read("time-invariant.dfsu", time=0)`.

In a NetCdf file you can be explicit about the dimensions, e.g. time can be a dimension with a single timestep, or have no time dimension, but in a dfs file, there will always be a start_time even if we want to interpret the file as time invariant.

It is a not easy to come up with a good design for singleton dimensions, but I hope this is good enough.

**Comment by Hendrik1987** [comment]
Your suggestion `mikeio.read("time-invariant.dfsu", time=0)` works.

Both, `ds` and `ds2` above carry the information on the first time step, or not? Only the array shape is different.

I personaly would expect a behaviour where after write and read `ds2` is the same as `ds`. But the current design is definetely good enough!

**Comment by ecomodeller** [comment]
We are considering ways to improve consistency with xarray, currently experimenting with a dfs engine for dfs{2,3].

It could be as simple as:

```python
import xarray as xr
import mikeio

ds = xr.open_dataset("some_meteo.dfs2", engine="mikeio")
```
That would be great for structured data, but I am still searching for the optimal solution for unstructured meshes, let me know if you have any suggestion.

**Comment by Hendrik1987** [comment]
You likely know that this topic is also realized by xarray: https://docs.xarray.dev/en/stable/roadmap.html#specific-needs
Maybe also worth to look at xarray extension approach by Deltares: https://github.com/Deltares/xugrid

In general, I find your `geometry` approach in `mikeio` much tidier than having additional dimensions like `x_nodes` etc. to store the mesh in the same ds. But keeping it seperate will require to also modify the geometry for all the `.sel` and aggregation methods. So, unfortunately no, no really good ideas right now from my end. But I am happy to test and contribute once your experiments mature :-)
