### ISSUE TITLE
Ideas for dfsu and mesh

### ISSUE THREAD

**Issue by jsmariegaard** [DHI/mikeio#65]
Dfsu and Mesh classes have very similar appearance and functionality. Should they inherit from the same base class or should Dfsu simply inherit Mesh like https://github.com/robjameswall/dhitools/blob/master/dhitools/dfsu.py ? 

I think the Mesh/Dfsu class should have a number of properties like node_coordinates, element_coordinates, number_of_layers etc. Most of these should be set on read() (those that does not require any computation) others should be set (lazy) only when the user requests it first time (e.g. element_coordinates can take time on large meshes). When the user calls find_closest_element_index() which needs element_coordinates, it will be built on the first run (and therefore take some time) subsequent runs will be fast as element_coordinates is already there. 

Furthermore, when creating a new dfsu file from a Dfsu object which have already read a dfsu file (that would be a typical workflow) I would like create() to use these properties instead of reading in a sourcefile again. 

What do you think?

**Comment by ecomodeller** [comment]
Would this API make it easier?

```python
dfsu = Dfsu("mysourcefile.dfsu") # 1. add source file to constructor (either dfsu or mesh)

# Read some of the items
ds = dfsu.read(["Current speed","Salinity"]) # 2. Make items the first argument, names or numbers

# Do some processing of the dataset
...

# Create a new file from this dataset
dfsu.create("mynewfile.dfsu", ds) # 3. source file from constructor, item info from dataset
```

**Comment by jsmariegaard** [comment]
See #67 for further discussion...
