### ISSUE TITLE
Select/filter Dataset on time and/or items

### ISSUE THREAD

**Issue by jsmariegaard** [DHI/mikeio#68]
If I have a Dataset from a dfsu file, I can very conveniently filter on element_ids and save to new file. That's great!

    selds = ds.isel(idx=elem_ids)
    dfs.write(newfile, selds, element_ids=elem_ids)

I would like to similarly filter on timesteps and/or items as a method on the Dataset class returning a new Dataset. Something like this:

     selds = ds.select_steps(range(4,19)) 

or 

     selds = ds.select_steps('2018-1-1','2018-2-1')

or similar with a daterange or something. And likewise on items either by name or number. These selections can then be chained: 

    selds = ds.select_items('water level').select_steps('2018-1-1','2018-2-1').isel(element_ids)

Or in a single method like this:

    selds = ds.select(items=['water level'], time_steps=['2018-1-1','2018-2-1'], element_ids=element_ids)

What do you think?

**Comment by ecomodeller** [comment]
I think we should try to mimic the functionality of xarray http://xarray.pydata.org/en/stable/generated/xarray.Dataset.sel.html

Since we are not loading the data lazily (yet, at least) the filtering is most efficient to do while reading the data and not on the Dataset, but this should be possible, for convenience.

**Comment by ecomodeller** [comment]
```
Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32

>>> import mikeio
>>> ds = mikeio.read("tests/testdata/HD2D.dfsu")
>>> ds
DataSet(data, time, items)
Number of items: 4
Shape: (9, 884)
1985-08-06 07:00:00 - 1985-08-07 03:00:00
>>> ds.items
[Surface elevation <Surface Elevation> (meter), U velocity <u velocity component> (meter per sec), V velocity <v velocity component> (meter per sec), Current speed <Current Speed> (meter per sec)]
>>> ds2 = ds[['Surface elevation','Current speed']] # item selection
>>> ds2.items
[Surface elevation <Surface Elevation> (meter), Current speed <Current Speed> (meter per sec)]
>>> len(ds2)
2
>>> ds3 = ds2.isel([0,1,2], axis=0) # temporal selection
>>> ds3
DataSet(data, time, items)
Number of items: 2
Shape: (3, 884)
1985-08-06 07:00:00 - 1985-08-06 12:00:00
>>> ds4 = ds3.isel([100,200], axis=1) # element selection
>>> ds4
DataSet(data, time, items)
Number of items: 2
Shape: (3, 2)
1985-08-06 07:00:00 - 1985-08-06 12:00:00
>>>
```

**Comment by jsmariegaard** [comment]
Nice!

Another thing came to my mind: 3d dfsu files (and their Dataset) have a z-item which is node-based. When I do 

    ds3.isel([100], axis=1)

I will select node 100 for the z-item and element 100 for remaining items... that is not optimal. But I guess it is not very elegant to let the Dataset hold the element_table as well so it can look up which nodes are related to element 100 ???

**Comment by ecomodeller** [comment]
I think the dataset should eventually, know what type of geometry is represents, but I think that is for another day.

Should we skip z-item for now, to avoid confusion and a very likely `IndexError`?
