### ISSUE TITLE
Page not found at https://dhi.github.io/mikeio/dfs1.html

### ISSUE THREAD

**Issue by esaesdhi** [DHI/mikeio#686]
**Describe the bug**
Page not found at https://dhi.github.io/mikeio/dfs1.html. This link is available on https://dhi.github.io/getting-started-with-mikeio/dfs1.html page : "See [Dfs1 in MIKE IO Documentation](https://dhi.github.io/mikeio/dfs1.html)".

**System information:**
 Using Microsoft Edge.

**Comment by ecomodeller** [comment]
Thanks, it has moved to https://dhi.github.io/mikeio/api/Dfs1.html#mikeio.Dfs1

________________________________
From: esaesdhi ***@***.***>
Sent: Thursday, April 11, 2024 4:47:33 PM
To: DHI/mikeio ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [DHI/mikeio] Page not found at https://dhi.github.io/mikeio/dfs1.html (Issue #686)


Describe the bug
Page not found at https://dhi.github.io/mikeio/dfs1.html. This link is available on https://dhi.github.io/getting-started-with-mikeio/dfs1.html page : "See Dfs1 in MIKE IO Documentation<https://dhi.github.io/mikeio/dfs1.html>".

System information:
Using Microsoft Edge.

**Comment by ecomodeller** [comment]
Fixed
