### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by sureshphdau** [DHI/mikeio#687]
I am unable to install mikeio in recently installed Anaconda application. 
Throwing the following error. Any suggestions please. 

>>pip install mikeio
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)'))': /simple/mikeio/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)'))': /simple/mikeio/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)'))': /simple/mikeio/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)'))': /simple/mikeio/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)'))': /simple/mikeio/
Could not fetch URL https://pypi.org/simple/mikeio/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/mikeio/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)'))) - skipping
ERROR: Could not find a version that satisfies the requirement mikeio (from versions: none)
ERROR: No matching distribution found for mikeio
Could not fetch URL https://pypi.org/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)'))) - skipping

**Comment by bhlevca** [comment]
Mikeio is installed with pip, it is not supported with conda anymore.

Bogdan

**Comment by bhlevca** [comment]
> I did not try with conda, I tried the following command in the Python command prompt.
You mentioned Anaconda as you can see in the quoted line above.  It means that you have Conda installed. You are not giving enough information about your environment. Therefore, the answer refers to the information you have provided.

Until you provide enough information about your Python environment, we can only guess. 
In terms of Python, you need to have a Python environment from https://Python.org and it is better to create a separate virtual  environment for your application using `python -m venv venv` and use it after activating it with `venv\Scripts\activate`

I tried your command in Windows Powershell and it works just fine. You need to fix your Python environment first.
