### ISSUE TITLE
Error in DataArray.__init__ if data is the last column of a dataframe

### ISSUE THREAD

**Issue by rolffank** [DHI/mikeio#705]
I have converted a pandas dataframe to a mikeio Dataset. But I cannot convert the last column to a mikeio DataArray.
The structure of the dataframe is as follows:
```
<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 16637 entries, 2024-04-24 11:40:00 to 2024-06-21 06:00:00
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Q       16637 non-null  float64
 1   Vacc    16637 non-null  float64
 2   v       16637 non-null  float64
 3   h       16637 non-null  float64
 4   T       16637 non-null  float64
dtypes: float64(5) 
```
I converted the columns by:
```
item = ItemInfo("Durchfluss", EUMType.Discharge, EUMUnit.liter_per_sec, data_value_type=DataValueType.Instantaneous)
d_Q = mikeio.DataArray(data=df.Q, time=df.index, item=item)
```
etc. but for column T I get the following error: TypeError: Data must be np.ndarray, e.g. numpy array, but it lacks properties: dtype
```
item = ItemInfo("Temperatur", EUMType.Temperature, EUMUnit.degree_Celsius, data_value_type=DataValueType.Instantaneous)
d_T = mikeio.DataArray(data=df.T, time=df.index, item=item)
```
Afterwards I use the following code to create a dfs0 file (but without d_T because of the error)
```
ds = mikeio.Dataset([d_Q, d_Vacc, d_v, d_h])
ds.to_dfs(filename)
```
I have no idea why the column 'T' doesn't work. Because it's the last or of type degree_Celsius? It should be of the same type like the other columns.    
  
Thanks providing mikeio, it's very helpful,    
Rolf

**Comment by jsmariegaard** [comment]
Hi Rolf, that is odd. Have you tried to convert directly to dfs0? 

    df.to_dfs0("output/naples_fl_eum.dfs0",
            items=[
                   ItemInfo(EUMType.Temperature),
                   ItemInfo(EUMType.Precipitation_Rate, EUMUnit.inch_per_day)]
           )

**Comment by jsmariegaard** [comment]
You could also test with df.T.to_numpy() optionally with dtype argument - see https://pandas.pydata.org/docs/reference/api/pandas.Series.to_numpy.html#pandas.Series.to_numpy

**Comment by ecomodeller** [comment]
Maybe the name "T" is interfering with transpose method `DataFrame.T` https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.T.html
🤔

**Comment by jsmariegaard** [comment]
> Maybe the name "T" is interfering with transpose method `DataFrame.T` https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.T.html 🤔

Good point - in that case safer to refer to that series with df["T"]
