### ISSUE TITLE
Concat bug with mikeio>2.0

### ISSUE THREAD

**Issue by daniel-caichac-DHI** [DHI/mikeio#718]
Hi, 

I think there is an issue with generic.concat and dfs0 files at least.
The documentation of `generic.concat` says that it should work  with  `keep` either `first` or `last`

![image](https://github.com/user-attachments/assets/586e6e99-ecc3-444e-96bb-8e58cc948a33)
But the documentation of `_dataset.py` says that it only works with last

![image](https://github.com/user-attachments/assets/d15a809a-edd6-4bc8-86e6-655a30fe9fe9)

Well, I am using `generic.concat`, and instead of calling `generic.concat`, it is going to `dataset.concat` apparently

![image](https://github.com/user-attachments/assets/c2f6ab95-d9ab-4860-ae7d-a7545f1fcf09)

* Just tried with mikeio 2.0.0 and 2.0.1, same conclusion.

* I downgraded to 1.7.1 and same script now works fine

**Comment by ecomodeller** [comment]
Thx for reporting this, the reason for this was that concatenating dfs0 files looping over every timestep is a bit slow. But I missed the fact that only one keep option was available.
