### ISSUE TITLE
Docstring of Grid1D shows non-existent attributes

### ISSUE THREAD

**Issue by jsmariegaard** [DHI/mikeio#723]
The docstring of Grid1D https://github.com/DHI/mikeio/blob/7a01cc74d92470ba6ecc1d6b86fb94c478ba7051/mikeio/spatial/_grid_geometry.py#L71 shows non-existent attributes like x0, node_coordinates and axis_name. I don't know why these properties were removed but the doctring should be consistent with the implementation.

**Comment by ecomodeller** [comment]
The docstring refers to parameters to the `__init__` method, not properties.
