### ISSUE TITLE
Temporal subsetting without pocket calculator

### ISSUE THREAD

**Issue by ecomodeller** [DHI/mikeio#74]
**Is your feature request related to a problem? Please describe.**
```
>>> dfs = Dfsu("foo.dfsu")
>>> dfs
Dfsu2D
...
Time: 9 steps with dt=9000.0s
      1985-08-06 07:00:00 -- 1985-08-07 03:00:00
>>> ds = dfs.read(items=[0, 3], time_steps=list(range(2,8)))
>>> ds
<mikeio.DataSet>
Dimensions: (6, 884)
Time: 1985-08-06 12:00:00 - 1985-08-07 00:30:00
```
**Describe the solution you'd like**
```
>>> ds = dfs.read(items=[0, 3], time_range="1985-08-07 12:00:1985-08-08 00:00")
>>> ds
<mikeio.DataSet>
Dimensions: (6, 884)
Time: 1985-08-06 12:00:00 - 1985-08-07 00:30:00
```

Things to consider:
How to best handle if selected timesteps are not available.

**Comment by jsmariegaard** [comment]
Should the timesteps-argument perhaps be more flexible (accept different types of input).? Like pandas can accept different kinds of input when you filter on a time axis.

    ds = dfs.read(items=[0, 3], time_steps='1985-08-07:1985-08-08') 

or 

    ds = dfs.read(items=[0, 3], time_steps='1985-08-07') 

or 

    ds = dfs.read(items=[0, 3], time_steps=[5,6]) 

And Dataset should then be able to select in the same way.

**Comment by jsmariegaard** [comment]
It should also take datetimes or date_ranges

    pd.date_range(start="2018-09-09",end="2020-02-02")

And notice the quite simple "start" and "end" here. Often you would want exactly that: either a start or an end.
