### ISSUE TITLE
Support for PFS files

### ISSUE THREAD

**Issue by ecomodeller** [DHI/mikeio#77]
Read pfs file into suitable python data structure. A dictionary is simple, but a bit clumsy to use for deeply nested structures. Any suggestions?
```
from mikeio import Pfs

d = Pfs("foo.m21fm")

sources = d["FemEngineHD"]["HYDRODYNAMIC_MODULE"]["SOURCES"]

n_sources = sources["number_of_sources"]

for i in range(n_sources):
  key = f"SOURCE_{i+1}"
  source = sources[key]
  name = source["name"]
```

Or perhaps:
```
m = Pfs("foo.m21fm")
m["FemEngineHD/HYDRODYNAMIC_MODULE/SOURCES"]
```

Or:

```
p = Pfs("foo.m21fm")
p.FemEngineHD.HYDRODYNAMIC_MODULE.SOURCES
```

One additional idea is to strip out unused modules during read

```
p = Pfs("foo.m21fm", strip=True)

p['PARTICLE_TRACKING_MODULE']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'PARTICLE_TRACKING_MODULE'
```

**Comment by jsmariegaard** [comment]
I would really like to have this feature!

For MIKE FM setups you have only one root element e.g. FemEngineHD and beneath that typically just a few sections: 

    [DOMAIN]
    [TIME]
    [MODULE_SELECTION]
    [HYDRODYNAMIC_MODULE]
    [DATA_ASSIMILATION_MODULE]

It would be convenient if I could access these simply by 

    pfs.domain
    pfs.time
    pfs.module_selection
    pfs.HD
    pfs.DA

Furthermore, I would like to get simple dataframes from typical lists that occur in the pfs files, e.g.

    df = pfs.HD.get_sources()
    df = pfs.HD.get_outputs(included_only=True)

This could be used for plotting all sources and outputs on a map... 

I would also like to get lists of input files: 

    filenames = pfs.get_input_files()

I would be great if you could easily search - similar to what you can with EUMTypes in mikeio :-)

**Comment by ecomodeller** [comment]
![pfs](https://user-images.githubusercontent.com/614215/92734215-9e8eb880-f378-11ea-9759-03a99f85d7fa.gif)

**Comment by Elsafti** [comment]
I have extended a module originally developed by Alex to read PFS files. The interface is a little bit clumsy but it is because the PFS structure allows for multiple keys of same name at the same level, which is something needed for some engines. So its use looks something like this:

FRCsetup[['[FrequencyResponseCalculator]','[VESSEL_CONFIGURATION]','[VESSEL_1]','[VESSEL_CHARACTERISTICS]','vessel_grid']]='|.\\fishfarm1unit.grd|'

In this way an index of the key order can be input after the key.

I have also developed a dictionary type module but this is not helpful with repeating keys because Python dictionaries assume keys are uniqe which isn't the case with PFS.  
Setup433['M21MooringAnalysis']['PORT_DATA']['FENDERS']

Of course what you have is much nicer but how do you manage repeated keys?

**Comment by ecomodeller** [comment]
Which engines uses repeated keys?

Are the sections or variables repeated, or both?
```
[FOO]
  [BAR]
    somevar = 1.0
    somevar = 1.5 // oops, a repeated variable
  Endsect // BAR

  [BAR] // oops, a repeated section
    somevar = 1.0
    somevar = 1.5
  Endsect // BAR
EndSect // FOO
```

**Comment by jsmariegaard** [comment]
I don't think this is possible with MIKE FM. 

Maybe @JesperGr knows about possibility of repeated keys and/or section in the pfs format?

**Comment by Elsafti** [comment]
I quote the MIKE SDK documentation page 33:

> Names of targets, sections and keywords need not be unique: Having a list of data is often stored as a set of sections or keywords with the same name.

Which I have met in a few input PFS files. As I said, I have a running module that works and can gladly pass it on. It is just not as pretty as target.section.subsection.parameter. But this can be enhanced if needed! I mean given enough recources!

**Comment by JesperGr** [comment]
Several engines and tools use PFS with repeated keys and sections. Of engines, M11, MHYDRO, MFLOOD. And then also lots of tools, like plot composer.

Other engines tend to name sections including a number, typicially defining a number keyword, and then a number of matching sections, for example. 

```
         number_of_constituents = 2
         [CONSTITUENT_1]
         EndSect  // CONSTITUENT_1

         [CONSTITUENT_2]
         EndSect  // CONSTITUENT_1
```

On top of that, if you want full PFS support, also the CLOB functionality must be considered.

**Comment by ecomodeller** [comment]
Some support for PFS is now available. Open a new issue, with specific problems or feature requests.
