### ISSUE TITLE
Collect functionality from similar (competing) libraries

### ISSUE THREAD

**Issue by ecomodeller** [DHI/mikeio#8]
dhitools seem to have a lot of useful functionality

https://github.com/robjameswall/dhitools
https://pypi.org/project/dhitools/

**Comment by j08lue** [comment]
> dhitools seem to have a lot of useful functionality

Yes. The library is well maintained and well documented. So why copy? Just use it...

**Comment by j08lue** [comment]
sorry, did not mean to close

**Comment by rhaDHI** [comment]
Seems that https://github.com/robjameswall/dhitools could benefit from mikeio. But mikeio should avoid the GDAL and geopandas dependencies and not consume dhitools, or did you decide on something here?

**Comment by rhaDHI** [comment]
I needed to load a dfs0, scale the time series data and write a new dfs0 file. I compiled @jsmariegaard 's github.com/DHI/dfs-utils instead and used from python. Maybe these tools can be merged as well?

**Comment by ecomodeller** [comment]
GDAL and geopandas seems difficult to install via pip, and I don't want to make `mikeio` only available via conda. Thus, I think we have to leave GIS functionality out of `mikeio`.

Is there any other functionality from dhitools that we should include in `mikeio` somehow? Or close this issue?

**Comment by j08lue** [comment]
> GDAL and geopandas seems difficult to install via pip

Only on Windows. On Linux there are by now zero issues with that (binary wheels galore).

**Comment by j08lue** [comment]
Still, avoiding very heavy dependencies that are only needed for an isolated set of features is a great idea. You can still ease the interface to e.g. `GeoDataFrames`, by returning dictionaries to directly create them from.

**Comment by jsmariegaard** [comment]
To qualify this discussion a bit more, I have tried to collect some important functionality in other mike libraries in the below lists. Please extend as needed. With such a list, we can prioritize what functionalities we would like to port to mikeio. 

dhitools by robjameswall https://github.com/robjameswall/dhitools
* dfsu-to-grid interpolation 
* interpolate from raster (e.g. to mesh)
* to_geodataframe
* dfsu: node_table
* item aggregate statistics (for timesteps or all)

DHI Matlab toolbox https://github.com/DHI/DHI-MATLAB-Toolbox
* Mesh: mzReorderMesh, mzRefineMesh
* Mesh: mzMeshAnalyse
* xyz: mzReadxyz, mzWritexyz
* header manipulation? (like custom blocks)

mikepy by Florian Monetti (DHI internal)
* re-projection
* calculate various statistics
* get_custom_blocks, set_custom_blocks
* xlsx_to_dfs0
* csv_to_dfs0
* dfsu_to_shape (GDAL)
* dfs2_to_raster (GDAL)
* exceedance_probs_to_dfs

**Comment by rhaDHI** [comment]
Nice. One way to prioritize could be to create an issue for each feature described with a few sentences and maybe with code snippets from the original source. If users and contributors really need these features then they will get implemented eventually or commented on in the issue. If there is a description there is a better chance someone might grab it. Maybe as part of a bigger related feature they are working on.

**Comment by ecomodeller** [comment]
## Annotated list
Implemented = ✔️ 
Notebook example = 📓 

### dhitools by robjameswall https://github.com/robjameswall/dhitools

* dfsu-to-grid interpolation
* interpolate from raster (e.g. to mesh)
* to_geodataframe 📓 
* dfsu: node_table
* item aggregate statistics (for timesteps or all)

### DHI Matlab toolbox https://github.com/DHI/DHI-MATLAB-Toolbox
* Mesh: mzReorderMesh, mzRefineMesh  
* Mesh: mzMeshAnalyse
* xyz: mzReadxyz, mzWritexyz :heavy_check_mark: #93
* header manipulation? (like custom blocks)

### mikepy by Florian Monetti (DHI internal)
* re-projection
* calculate various statistics
* get_custom_blocks, set_custom_blocks
* xlsx_to_dfs0 :heavy_check_mark: *pd.read_excel + df.to_dfs0*
* csv_to_dfs0 :heavy_check_mark: *pd.read_csv + df.to_dfs0*
* dfsu_to_shape (GDAL) :notebook:
* dfs2_to_raster (GDAL)
* exceedance_probs_to_dfs

**Comment by jsmariegaard** [comment]
## Annotated list
Implemented = ✔️
Notebook example = 📓
 
### dhitools by robjameswall https://github.com/robjameswall/dhitools
* dfsu-to-grid interpolation ✔️, 📓 
* interpolate from raster (e.g. to mesh)
* to_geodataframe 📓
* dfsu: node_table
* item aggregate statistics (for timesteps or all)
 
### DHI Matlab toolbox https://github.com/DHI/DHI-MATLAB-Toolbox
* Mesh: mzReorderMesh, mzRefineMesh
* Mesh: mzMeshAnalyse
* xyz: mzReadxyz, mzWritexyz ✔️ #93
* header manipulation? (like custom blocks)
 
### mikepy by Florian Monetti (DHI internal)
* re-projection ✔️#119 for dfs2
* calculate various statistics
* get_custom_blocks, set_custom_blocks
* xlsx_to_dfs0 ✔️ _pd.read_excel + df.to_dfs0_
* csv_to_dfs0 ✔️ _pd.read_csv + df.to_dfs0_
* dfsu_to_shape (GDAL) 📓
* dfs2_to_raster (GDAL)
* exceedance_probs_to_dfs

### MIKE Zero 
* Data Manager: create dfsu from mesh ✔️
* Data extraction FM
  - dfsu-2d
    - extract dfs0: discrete ✔️, interpolated (✔️)
    - extract dfs1: (✔️)
    - extract dfs2: (✔️ but not if the file is not too big)
    - extract dfsu-2d: ✔️
  - dfsu-3d
    - extract dfs0: discrete ✔️, interpolated (✔️)
    - extract dfs1: (✔️)
    - extract dfs2 transect 
    - extract dfsu transect 
    - extract dfsu volume ✔️
    - extract dfs3 

### MIKE Zero toolbox
* TxConc: Concatenation of dfs files ✔️
* Extraction from dfs123 (✔️)
* Time series: Interpolate time series ✔️
* Transformation: rotate grid (✔️)

### MIKE tools in bin folder (no GUI)
* DataTrackExtractionFM ✔️#121 for dfsu - dfs2 still missing
* DataVerticalAveragingFM 
  - extract specific layer: ✔️, 📓
* DataConcatenationFM ✔️
* DataCalculationFM ✔️ 
* DataExceedenceFM
* DataStatisticsFM ✔️
* DataMergeFM 
* DfsuToNetCDF 📓
* DfsuToAscii ✔️

**Comment by ecomodeller** [comment]
It is apparent that there is a lot of useful functionality in MIKE IO. I will close this issue and we can open more specific feature requests as the need arises.
