### ISSUE TITLE
Rename TimeStep Enum to TimeStepUnit

### ISSUE THREAD

**Issue by jsmariegaard** [DHI/mikeio#83]
Minor thing: I suggest we rename eum TimeStep class to TimeStepUnit

    class TimeStepUnit(IntEnum)

**Comment by jsmariegaard** [comment]
https://github.com/DHI/mikeio/blob/master/mikeio/eum.py#L29

**Comment by ecomodeller** [comment]
Fine by me, I never use anything else than seconds anyway...
