### ISSUE TITLE
multipolygon to geopandas dataframe to shapefile

### ISSUE THREAD

**Issue by anneverheijen** [DHI/mikeio#84]
**Is your feature request related to a problem? Please describe.**
During today's blue cafe I saw there is already a feature to import the mesh (maybe also dfsu?) into a multipolygon. This multipolygon can be easily saved as shapefile (one of the questions was how). I think this could be a useful feature.

**Describe the solution you'd like**
I have attached some code I've used with py-dhi-dfs from a while ago. Therefore, the code is not compatible with the current mikeio. However, I think the principle can be easily copied. This is also something I would happily do myself, but not this week.
 
A list of polygons can be transferred into a geopandas dataframe, see code below. After that you can add data to the dataframe and save it, see code below. This list of polygons can be constructed from the multipolygon, [see this question on stackoverflow](https://stackoverflow.com/questions/38930192/how-to-extract-polygons-from-multipolygons-in-shapely)

**Describe alternatives you've considered**
None. For me geopandas is the way to make shapefiles

**Additional context**
example code is attached (not 100% compatible with mikeio)
[example_dfsu_to_shp.txt](https://github.com/DHI/mikeio/files/5223458/example_dfsu_to_shp.txt)

**Comment by ecomodeller** [comment]
Thanks for the comment and for participating in the BLUE café!
I made a [notebook](https://github.com/DHI/mikeio/blob/master/notebooks/Dfsu%20-%20Export%20to%20shapefile.ipynb) that I think solves this problem using the current version of mikeio and geopandas.

What do you think?

**Comment by jsmariegaard** [comment]
Good stuff, @anneverheijen, we should definitely have that!

**Comment by anneverheijen** [comment]
@ecomodeller That's really fast! The notebook is great. The example is clear and you only need a few lines of code.

@jsmariegaard Thanks, I'm happy to contribute! 

I'm not quite sure it pays off to make a method out of it (".to_gdf()" or something), as the notebook shows only a few lines of code are needed. What do you think?

**Comment by ecomodeller** [comment]
For now I will leave it as a notebook.
