### ISSUE TITLE
Return Figure and Axes for plot methods

### ISSUE THREAD

**Issue by georgebv** [DHI/mikeio#87]
**Is your feature request related to a problem? Please describe.**
I want to be able to edit plots generated by mikeio. I would also like to save figures as `fig.savefig`.

**Describe the solution you'd like**
Please return Figure and Axes (or list/tuple of Axes) objects when calling `.plot*` methods.

**Comment by jsmariegaard** [comment]
Is it enough to return just the axes? - I think this is common by other packages such as xarray and pandas...

You can get the fig object from the axes if you need it.

**Comment by jsmariegaard** [comment]
The dfsu/mesh plot now return axes: 

https://github.com/DHI/mikeio/blob/a51baba7ba2004d18c19fb9febac043e70b02f1f/mikeio/dfsu.py#L1246

**Comment by ecomodeller** [comment]
I am trying to understand when it is necessary to return the figure object.

Isn't this sufficient?
```
dfs = Dfsu("myfile.dfsu")
dfs.plot()
plt.savefig("myplot.png")
```
![oresund_bathy](https://user-images.githubusercontent.com/614215/95826049-0c405280-0d32-11eb-8489-dbc67db10de2.png)
