### ISSUE TITLE
Creating an ndarray from ragged nested sequences is deprecated

### ISSUE THREAD

**Issue by ecomodeller** [DHI/mikeio#88]
https://github.com/DHI/mikeio/blob/90f39e349ea0fbc00d37b6d4887042116e4d48dd/mikeio/dfsu.py#L866

> dfsu.py:873: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
>     e2_to_e3 = np.array(e2_to_e3)
>

**Comment by jsmariegaard** [comment]
Right, could you suggest a solution?

**Comment by ecomodeller** [comment]
1 . regular python list of lists (but does not support indexing with array) 
2.  Explicit `e2_to_e3 = np.array(e2_to_e3, dtype="object") `

**Comment by jsmariegaard** [comment]
yes, well the reason to have it as arrays was to use it for slicing...

**Comment by jsmariegaard** [comment]
Closed by #108
