### ISSUE TITLE
Creating .dfsu based on mesh and timeseries data

### ISSUE THREAD

**Issue by AL89** [DHI/mikeio#96]
Hi

I am currently trying to invoke a method to specify timeseries data (e.g. rain) on specific regions, and then export it to a new .dfsu file. I tried to follow this doc from section "Store result in a new Dfsu file".
https://github.com/DHI/mikeio/blob/master/notebooks/Dfsu%20-%20Distance%20to%20land.ipynb

The difference between the above and my problem is that I have multiple timesteps whereas the above only have 1.
From the _.dfsu.py_ file there is written in line 1616-1617 in the `write` function:
```
data: list[np.array] or Dataset
            list of matrices, one for each item. Matrix dimension: time, x
```
So, my `data` numpy array has the dimensions `(361,39324)` (time, x) which corresponds to the description above, I believe? I only have one item and my time array is 361 long, so when I do the `dfsu.write` command I get this printed error/warning: `too many indices for array: array is 1-dimensional, but 2 were indexed`. I can't see what's the issue, but here is my code:

```
from mikeio import Dfsu, Mesh, Dfs0
import geopandas as gpd
import numpy as np

MESH_FILE ='MESH_Dalum_RAW.mesh'
dfs0 = Dfs0('LHA_2_T100_CDS_kobling.dfs0')
ts = dfs0.read()
start_time = ts.time[0]
dt = (ts.time[1] - start_time).seconds
tsdf = ts.to_dataframe()
nts = len(ts.time)

mesh = Mesh(MESH_FILE)
mp = mesh.to_shapely()
ne = mesh.n_elements

mp_gpd = gpd.GeoSeries(list(mp))

rf = gpd.read_file('regnfordeling_dalum.shp')
rf.set_index('ID',inplace=True)

data = np.empty([nts,ne])
vec_index = []
for t in range(nts):
    mesh_data = np.zeros(ne)
    
    for i,p in enumerate(rf.index): # Loop number of polygons
        try:
            mp_index = vec_index[i]
        except: # Only does this once for each polygon
            intsects = mp_gpd.within(rf.loc[p].geometry)
            mp_ints = mp_gpd.loc[intsects]
            mp_index = list(mp_ints.index)
            vec_index.append(mp_index)
        mesh_data[mp_index] = ts[str(p)][t]
    
    data[t] = mesh_data
data[data==0] = np.nan

dfs = Dfsu(MESH_FILE)
outfile = 'test.dfsu'
items = [ItemInfo('Regnfordeling',itemtype=EUMType.Precipitation_Rate)]
dfs.write(outfile,data=data,start_time=start_time,dt=dt,items=items,title='Regnfordeling')
```

Notice that I tried to put `data` in a list - same result

The files in the code are in the uploaded zip-file.
[Dfsu_issue.zip](https://github.com/DHI/mikeio/files/5276391/Dfsu_issue.zip)

**Comment by ecomodeller** [comment]
Data should be a list of the same length as items. See solution and produced dfsu file in zip.

[resolved.zip](https://github.com/DHI/mikeio/files/5276551/resolved.zip)

## Relevant part
```
items = [ItemInfo("Regnfordeling", itemtype=EUMType.Precipitation_Rate)]
data = [data] # add this line

dfs.write(
    outfile, data=data, start_time=start_time, dt=dt, items=items, title="Regnfordeling"
)
```

**Comment by AL89** [comment]
@ecomodeller Well, thanks! Seems a little odd since I tried to put `data` in a list... obviously I didn't! :)
