### ISSUE TITLE
Error in creating dfs3 with proper grid spacing

### ISSUE THREAD

**Issue by spurgeondsk** [DHI/mikeio#98]
While creating the dfs3 file from other formats dx and dy could not be mentioned as error peeps. Because of this grid spacing mentioned as 1 degree by default. Why dx=dx, dy=dy is not working while creating the dfs3 file?

![mikeIO_error](https://user-images.githubusercontent.com/69499484/94438110-4cdd8f00-01bc-11eb-84cf-2ca416e116f0.png)

**Comment by ecomodeller** [comment]
Are you using the released version from pypi or the latest version from github?

The latest version uses dx, dy. 
https://github.com/DHI/mikeio/blob/d0acf1d207013aec4505c0fe9cb9c0b2f004619f/tests/test_dfs3.py#L38-L49

The released version looks like this
https://github.com/DHI/mikeio/blob/3d0fb6acc4435eb6142941a1c944b6ab7aabce76/tests/test_dfs3.py#L38-L50

**Comment by spurgeondsk** [comment]
Got it thank you, it seems I am using released version installed through pip.
